.travis.yml
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/RDM-1958
Addition of Travis CI configuration file.
```
[ ] Yes
[X] No
```

RDM-1958: Addition of Travis CI configuration

---

package.json
src/components/form/date-input/date-input.component.ts

enhanced date component to be able to handle incomplete dates 
https://tools.hmcts.net/jira/browse/RDM-2174
```
[ ] Yes
[x ] No
```

enhanced date component to be able to handle also incomplete dates

---

README.md

Update yarn link

---

package.json
src/components/footer/footer.component.ts
src/components/footer/footer.html
src/components/footer/footer.scss
src/components/header/header.component.ts
src/components/header/header.html
src/components/header/header.scss
src/components/navigation/navigation-item.scss
src/components/navigation/navigation.component.ts
src/components/navigation/navigation.html
src/components/navigation/navigation.scss
src/components/phase/phase.component.ts
src/components/phase/phase.html
src/components/phase/phase.scss

https://tools.hmcts.net/jira/browse/RDM-1851
Dependency note: This change has dependency with the change on ccd-case-management-web branch RDM-1851
The header should look like with similar dimensions as in: https://reform-pattern-library.herokuapp.com/
The existing menus should be moved to the black header part, as seen in the pattern library header with menu "Elements""components" etc.
Footer should look like with the similar design as shown in the UI design layout.
Header and Footer will follow the GOV.IN standards in terms of the desktop screen width, etc.
```
[ ] Yes
[x] No
```

RDM 1851: Header and footer needs to match Gov.Uk styling

---

RELEASE-NOTES.md
package.json

Add Release notes for Open Source

---

RELEASE-NOTES.md
package.json
src/components/footer/footer.html
src/components/navigation/navigation-item.scss
src/components/phase/phase.html

Rdm 1851 2

---

RELEASE-NOTES.md
package.json
src/components/form/date-input/date-input.component.ts
src/components/form/date-input/date-input.html

https://tools.hmcts.net/jira/browse/RDM-1149
This one is for adding additional hour, minute and second boxes to existing Date component
```
[ ] Yes
[X] No
```

RDM-1149 added dateTime support to Date component

---

RELEASE-NOTES.md
package.json
src/components/header/header.html
src/components/header/header.scss

https://tools.hmcts.net/jira/browse/RDM-1886
The sign out overlay interrupts the search functionality leading to mistaken Sign Outs.
```
[ ] Yes
[x] No
```

RDM-1886: Sign Out link redesign

---

.nyc_output/.gitkeep
.travis.yml
README.md
angular.json
package-lock.json
package.json
src/karma.conf.js
src/polyfills.ts
src/test.ts
src/tsconfig.spec.json
yarn.lock

This is part 2 of the README - this pr uploads code coverage report to codecov
```
[ ] Yes
[x] No
```

Allow Travis to upload coverage report to codecov

---

RELEASE-NOTES.md
package.json

https://tools.hmcts.net/jira/browse/RDM-1202
Changes to upgrade case ui toolkit for RDM-1202
```
[ ] Yes
[X] No
```

RDM-1202 - Release case ui toolkit

---

RELEASE-NOTES.md
package.json

https://tools.hmcts.net/jira/browse/RDM-3064
Case progression: Better component contract - Master release
```
[x] Yes
[ ] No
```

RDM-3064 Case progression: Better component contract - Master release

---

README.md
RELEASE-NOTES.md
demo/stubs/api.json
package.json
yarn.lock

New release.
```
[ ] Yes
[x] No
```

RDM-3230 Release new 2.1.0 version

---

.travis.yml
demo/README.md
demo/heroku-publish.sh
demo/package.json
demo/yarn.lock
package.json
yarn.lock

Downgrade yarn to fix mgmt web build.
```
[ ] Yes
[x] No
```

RDM-3230 Downgrade yarn.

---

README.md
RELEASE-NOTES.md
demo/README.md
package.json

New release
```
[ ] Yes
[x] No
```

RDM-3230 Release 2.2.0

---

src/shared/components/case-editor/case-create/case-create.component.spec.ts
src/shared/components/case-editor/case-create/case-create.component.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.html
src/shared/components/case-editor/case-edit/case-edit.component.ts
src/shared/components/case-editor/case-progress/case-progress.component.spec.ts
src/shared/components/case-editor/case-progress/case-progress.component.ts
src/shared/components/case-editor/domain/wizard.model.spec.ts
src/shared/components/case-editor/domain/wizard.model.ts
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/error/callback-errors.component.spec.ts
src/shared/components/error/callback-errors.component.ts

https://tools.hmcts.net/jira/browse/RDM-3000
https://tools.hmcts.net/jira/browse/RDM-3001
Process validate Request. Update CaseEventTrigger for future pages and editForm for previous pages update.
```
[ ] Yes
[X ] No
```

[PREVIEW] RDM-3000 MidEvent callback

---

RELEASE-NOTES.md
package.json

Update Release notes for v2.5.0

---

RELEASE-NOTES.md
package.json

RDM-3230 Small patch to export profile service.

---

src/shared/components/palette/label/label-field.component.spec.ts
src/shared/components/palette/label/label-field.html
src/shared/directives/substitutor/label-substitutor.directive.spec.ts
src/shared/directives/substitutor/label-substitutor.directive.ts
src/shared/directives/substitutor/services/label-substitution.service.spec.ts
src/shared/directives/substitutor/services/label-substitution.service.ts

Reverts hmcts/ccd-case-ui-toolkit#106

Revert "Rdm 2323 - Support field concatenation in List / results views "

---

RELEASE-NOTES.md
demo/package.json
demo/server.js
demo/stubs/api.json
demo/yarn.lock
package.json
src/shared/components/case-editor/case-create/case-create.component.spec.ts
src/shared/components/case-editor/case-create/case-create.component.ts
src/shared/components/case-editor/services/cases.service.ts

https://tools.hmcts.net/jira/browse/RDM-3427
UI Toolkit: Use Start Event API v2
```
[ ] Yes
[x] No
```

Rdm 3427 UI Toolkit: Use Start Event API v2

---

src/shared/components/palette/label/label-field.component.spec.ts
src/shared/components/palette/label/label-field.html
src/shared/directives/substitutor/label-substitutor.directive.spec.ts
src/shared/directives/substitutor/label-substitutor.directive.ts
src/shared/directives/substitutor/services/label-substitution.service.spec.ts
src/shared/directives/substitutor/services/label-substitution.service.ts

Reverts hmcts/ccd-case-ui-toolkit#157

Revert "Rdm 2323 based on latest master"

---

src/karma.conf.js
src/shared/directives/conditional-show/domain/conditional-show.model.spec.ts
src/shared/directives/conditional-show/domain/conditional-show.model.ts
src/shared/directives/substitutor/label-substitutor.directive.ts
src/shared/fixture/shared.fixture.ts
src/shared/services/fields/fields.utils.spec.ts
src/shared/services/fields/fields.utils.ts

https://tools.hmcts.net/jira/browse/RDM-2009
Update ccdConditionalShow directive to process complex fields
```
[ ] Yes
[ X] No
```

[PREVIEW] RDM-2009 ComplexType conditional show

---

src/shared/components/case-editor/case-edit-form/case-edit-form.html
src/shared/components/palette/base-field/field-read.component.spec.ts
src/shared/components/palette/collection/write-collection-field.component.spec.ts
src/shared/components/palette/collection/write-collection-field.component.ts
src/shared/components/palette/collection/write-collection-field.html
src/shared/components/palette/utils/is-read-only-and-not-collection.pipe.spec.ts
src/shared/components/palette/utils/is-read-only-and-not-collection.pipe.ts
src/shared/components/palette/utils/is-read-only.pipe.spec.ts
src/shared/components/palette/utils/utils.module.ts
src/shared/domain/definition/access-control-list.model.ts
src/shared/domain/definition/case-field.model.ts

https://tools.hmcts.net/jira/browse/RDM-3284
This task if for the FE. Checks the ACLs being delivered by the backend see (RDM-2455) to render the add buttons according to the user's rights.
Must be merged after [this PR.](https://github.com/hmcts/ccd-data-store-api/pull/253)
```
[ ] Yes
[X] No
```

RDM-3284 CRUD contract on Collection for Add new item

---

RELEASE-NOTES.md
package.json

Update version to 2.11.0

---

RELEASE-NOTES.md
package.json

bump version for toolkit 

---

package.json

bump version to 2.15

---

package.json

R introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

bump version to 2.17

---

src/shared/components/case-editor/case-edit-submit/case-edit-submit.html

Cf. Stuart
Reword CYA description
```
[ ] Yes
[x] No
```

Stuart: Remove `application` from CYA description

---

.travis.yml
package.json

https://tools.hmcts.net/jira/browse/RDM-3320
```
[ ] Yes
[ ] No
```

Use latest yarn and update minimum yarn version

---

RELEASE-NOTES.md
package.json

https://tools.hmcts.net/jira/browse/RDM-3675
bump version 
```
[ ] Yes
[X] No
```

bump version to 2.23.4

---

package.json

RDM-3821
bump version to 2.24.0
```
[ ] Yes
[ ] No
```

bump version to 2.24.0

---

RELEASE-NOTES.md
package.json

Update the Version to 2.24.1 
```
[ ] Yes
[x] No
```

Update version of toolkit to 2.24.1

---

RELEASE-NOTES.md
package.json

https://tools.hmcts.net/jira/browse/RDM-3430
bump version 2.27.1
```
[ ] Yes
[x] No
```

bump version to 2.27.1

---

demo/src/app/case-create-consumer.component.html
demo/src/app/case-create-consumer.component.ts
demo/src/app/core.component.html
demo/src/app/core.component.ts
demo/src/app/elements-documentation.scss
demo/src/style/app.scss
demo/src/style/vendor/prism.css

Self documenting case creation component.
```
[ ] Yes
[x]  No
```

Make demo app self documenting.

---

README.md
demo/README.md

Update demo README.

---

demo/README.md

Further cleanup of demo README.

---

RELEASE-NOTES.md
package.json

bump version 2.30

---

RELEASE-NOTES.md
package.json

Updated release details for RDM-3972 and RDM-3936
```
[ ] Yes
[x] No
```

Release notes and version updated

---

demo/src/app/app.module.ts
demo/src/app/app.routing.ts
demo/src/app/core.component.html
demo/src/app/core.component.ts
demo/src/app/create-case-filters-consumer.component.html
demo/src/app/create-case-filters-consumer.component.ts

https://tools.hmcts.net/jira/browse/RDM-3918
Added create case filters to the demo app. Documentation as well.
```
[ ] Yes
[x] No
```

Rdm 3918 Create Case Filters demo and documentation

---

package.json
src/shared/components/case-viewer/case-viewer.component.html
src/shared/components/case-viewer/case-viewer.component.spec.ts
src/shared/components/case-viewer/case-viewer.component.ts

https://tools.hmcts.net/jira/browse/RDM-4178
Changed caseviewer to accommodate changes to the event trigger
```
[ ] Yes
[x] No
```

RDM-4178 POC

---

RELEASE-NOTES.md
package.json

bump toolkit version 2.35

---

package.json

Update v2.28.0 

---

src/shared/components/case-viewer/case-viewer.component.spec.ts
src/shared/components/case-viewer/case-viewer.component.ts

https://tools.hmcts.net/jira/browse/RDM-4521
Added an extra condition for error management
```
[ ] Yes
[x] No
```

RDM-4521 fixed bug

---

RELEASE-NOTES.md
package.json

Adding release details and updating version

---

src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
src/shared/components/case-editor/case-edit-submit/case-edit-submit.html
src/shared/components/case-editor/case-edit.scss

https://tools.hmcts.net/jira/browse/RDM-3525
https://tools.hmcts.net/jira/browse/RDM-4486
**INC0443968**
Disable submit button for case event after it is clicked 
```
[ ] Yes
[x] No
```

RDM-3525 - disable submit button once submitted on a case event

---

RELEASE-NOTES.md
package.json

Update version to v2.41.1 RDM-3525

---

RELEASE-NOTES.md
package.json
src/shared/services/form/form-validators.service.spec.ts
src/shared/services/form/form-validators.service.ts

https://tools.hmcts.net/jira/browse/RDM-4591
Fixed to allow the special character for validations
```
[ ] Yes
[x] No
```

RDM-3325/4591: Fixed to allow the special characters for validations

---

demo/package.json
package.json
yarn.lock

Requested by the payment component. So that cosmetic changes pushed to a minor release would automatically be picked up by the next build
```
[ ] Yes
[ ] No
```

update payment component dependency management

---

RELEASE-NOTES.md

Update release notes.
```
[ ] Yes
[x] No
```

rdm-3940-update-release-notes

---

.travis.yml

Align top node 10 version with top Node 10 on Azure Webapps.
```
[ ] Yes
[ ] No
```

Bump highest Azure 10.x node to 10.15.2

---

RELEASE-NOTES.md
package.json

version-change

---

RELEASE-NOTES.md
package.json
src/shared/components/search-result/search-result.component.spec.ts
src/shared/components/search-result/search-result.component.ts

https://tools.hmcts.net/jira/browse/RDM-4786
https://tools.hmcts.net/jira/browse/RDM-4535
*Merged off RDM-4535*
applied fix for search result component
```
[x] Yes
[ ] No
```

Rdm 4786 fix for search result

---

.travis.yml

Suppress the analytics question when installing angular cli during a
Travis build.
```
[ ] Yes
[ ] No
```

Non-interative install of angular/cli in Travis

---

.travis.yml

See
https://docs.travis-ci.com/user/customizing-the-build#safelisting-or-blocklisting-branches
```
[ ] Yes
[ ] No
```

Build on master and tagged releases

---

RELEASE-NOTES.md
package.json

Update toolkit version to v2.51.1

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-editor/services/cases.service.ts

https://tools.hmcts.net/jira/browse/RDM-4336
Consume external POST Create Event endpoint in API v2
```
[ ] Yes
[x] No
```

RDM-4336 Consume the new external V2 Create Event endpoint.

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit/case-edit.component.ts
src/shared/services/fields/fields.purger.ts
src/shared/services/fields/fields.utils.ts

RDM-4781-Data not being shown on multi-select list

---

src/shared/components/palette/yes-no/write-yes-no-field.html
src/shared/directives/substitutor/services/placeholder.service.spec.ts
src/shared/directives/substitutor/services/placeholder.service.ts

https://tools.hmcts.net/jira/browse/RDM-5107
Fix field interpolation for placeholders pointing at collection items. Keep the scanning index in current processing context as opposed to zeroing in every new string to resolve processing.
```
[ ] Yes
[x] No
```

Rdm 5107 Collection in Label : First row of a the collection contains values from other rows

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/base-field/field-read.component.ts
src/shared/components/search-result/search-result.component.html
src/shared/components/search-result/search-result.component.ts

Reverts hmcts/ccd-case-ui-toolkit#385

Revert "RDM-5044 Add Promise then for Angular lifecycle to catchup."

---

src/shared/components/palette/yes-no/write-yes-no-field.html
yarn.lock

https://tools.hmcts.net/jira/browse/RDM-4279
This PR contains a fix for radio button focus order which occurs in case multiple radio groups are consecutively placed in a wizard page.
```
[ ] Yes
[X] No
```

RDM-4279 fix for [DAC] Focus Order

---

RELEASE-NOTES.md
package.json

UI Toolkit Release - Bumped up release version to 2.58.5

---

RELEASE-NOTES.md
package.json
src/shared/directives/conditional-show/domain/conditional-show.model.ts

RDM-4121 - fix undefined error

---

RELEASE-NOTES.md
package.json
src/shared/components/workbasket-filters/workbasket-filters.component.html
src/shared/components/workbasket-filters/workbasket-filters.component.spec.ts
src/shared/components/workbasket-filters/workbasket-filters.component.ts

https://tools.hmcts.net/jira/browse/RDM-5318
Changes to make Workbasket tolerant of missing defaults.
```
[ ] Yes
[x ] No
```

RDM-5318 - Changes to make Workbasket tolerant of missing defaults.

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/wizard-page-field-to-case-field.mapper.ts
src/shared/components/palette/address/write-address-field.component.spec.ts
src/shared/components/palette/address/write-address-field.component.ts
src/shared/components/palette/base-field/field-read-label.component.spec.ts
src/shared/components/palette/base-field/field-read-label.component.ts
src/shared/components/palette/complex/read-complex-field-collection-table.component.spec.ts
src/shared/components/palette/complex/read-complex-field-collection-table.component.ts
src/shared/components/palette/utils/is-read-only-and-not-collection.pipe.spec.ts
src/shared/components/palette/utils/is-read-only-and-not-collection.pipe.ts
src/shared/directives/conditional-show/domain/conditional-show.model.spec.ts
src/shared/directives/conditional-show/services/grey-bar.service.ts
src/shared/domain/definition/case-field.model.ts
src/shared/fixture/case-field-builder.ts
src/shared/fixture/index.ts
src/shared/fixture/shared.test.fixture.ts
src/shared/services/fields/fields.utils.ts
src/shared/services/order/order.service.ts

https://tools.hmcts.net/jira/browse/RDM-4073
Added utility methods isComplex and isCollection to CaseField. This required many changes to the test code due to the method used for CaseField creation in tests.
This PR is replacing the old stale PR which has gone way out of sync https://github.com/hmcts/ccd-case-ui-toolkit/pull/246
```
[ ] Yes
[X] No
```

RDM-4073 reworked branching from master

---

RELEASE-NOTES.md
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/PAY-1732
Telephony MVP Payments List
```
[ ] Yes
[X] No
```

PAY-1732 -> Upgrading the version for Telephony MVP

---

RELEASE-NOTES.md
package.json
yarn.lock

Reverts hmcts/ccd-case-ui-toolkit#404

Revert "PAY-1732 -> Upgrading the version for Telephony MVP"

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/base-field/field-read.component.ts

Reverts hmcts/ccd-case-ui-toolkit#413

Revert "RDM-5604 Fix {} instantiations for read-collection-XX components"

---

RELEASE-NOTES.md
package.json
yarn.lock

V2.58.13 clean and Pay version Upgrade

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/wizard-page-field-to-case-field.mapper.ts
src/shared/components/palette/address/write-address-field.component.spec.ts
src/shared/components/palette/address/write-address-field.component.ts
src/shared/components/palette/base-field/field-read-label.component.spec.ts
src/shared/components/palette/base-field/field-read-label.html
src/shared/components/palette/base-field/field-read.html
src/shared/components/palette/collection/collection-create-checker.service.spec.ts
src/shared/components/palette/collection/collection-create-checker.service.ts
src/shared/components/palette/collection/write-collection-field.component.spec.ts
src/shared/components/palette/collection/write-collection-field.component.ts
src/shared/components/palette/complex/read-complex-field-collection-table.component.spec.ts
src/shared/components/palette/complex/read-complex-field-collection-table.component.ts
src/shared/components/palette/complex/read-complex-field-collection-table.html
src/shared/components/palette/complex/read-complex-field-table.component.ts
src/shared/components/palette/complex/read-complex-field-table.html
src/shared/components/palette/complex/read-complex-field.component.spec.ts
src/shared/components/palette/complex/read-complex-field.component.ts
src/shared/components/palette/complex/read-complex-field.html
src/shared/components/palette/palette.module.ts
src/shared/components/palette/utils/is-read-only-and-not-collection.pipe.spec.ts
src/shared/directives/conditional-show/domain/conditional-show.model.spec.ts
src/shared/fixture/case-field-builder.ts
src/shared/fixture/index.ts
src/shared/fixture/shared.test.fixture.ts

This PR is for removing RDM-4073 changes from master and previously merged RDM-5310
RDM-4073 will be added back with another PR after extensive tests.
```
[ ] Yes
[X] No
```

RDM-5310 clean rework branch for removing RDM-4073 related changes

---

src/index.ts
src/shared/components/case-viewer/case-viewer.component.spec.ts
src/shared/components/case-viewer/case-viewer.component.ts
src/shared/components/case-viewer/case-viewer.module.ts
src/shared/components/case-viewer/services/case.resolver.spec.ts
src/shared/components/case-viewer/services/case.resolver.ts
src/shared/services/error/error-notifier.service.spec.ts
src/shared/services/error/error-notifier.service.ts
src/shared/services/error/index.ts
src/shared/services/index.ts

https://tools.hmcts.net/jira/browse/RDM-6350
Introduce new ErrorNotifierService that will notify CaseViewerComponent about any error that occurred during navigation done by the consumer of the CaseViewerComponent
```
[ ] Yes
[x] No
```

RDM-6350 Introduce new ErrorNotifierService and subscribe in CaseViewerComponent

---

src/shared/components/palette/case-link/case-link.module.ts
src/shared/components/palette/complex/complex.module.ts
src/shared/components/palette/complex/read-complex-field-collection-table.component.spec.ts
src/shared/components/palette/complex/read-complex-field-collection-table.component.ts
src/shared/components/palette/complex/read-complex-field-collection-table.html
src/shared/components/palette/palette.module.ts

https://tools.hmcts.net/jira/browse/RDM-5296
CaseLink was displayed as a text. This change will make it a link.
```
[ ] Yes
[ X] No
```

RDM-5296 - Table Collection View - Case Link is not displayed as a link

---

src/shared/components/palette/complex/read-complex-field-collection-table.component.spec.ts
src/shared/components/palette/complex/read-complex-field-collection-table.component.ts
src/shared/components/palette/complex/read-complex-field-collection-table.html

https://tools.hmcts.net/jira/browse/RDM-5293
Bug fix as in the ticket
```
[ ] Yes
[ X] No
```

RDM-5293 - Table Collection View - Data from the first complex type is repeated for all collection items

---

.travis.yml

Allow travis failure of Latest Node LTS on toolkit builds

---

RELEASE-NOTES.md
package.json

Bumped up toolkit version

---

demo/src/style/app.scss
src/shared/components/palette/document/write-document-field.component.spec.ts
src/shared/components/palette/document/write-document-field.component.ts
src/shared/components/palette/document/write-document-field.html
src/shared/services/document-management/document-management.service.ts

RDM-1280: Wizard page should only allow Continue when all documents have been uploaded
    [RDM-1280] (https://tools.hmcts.net/jira/browse/RDM-1280).

Rdm 1280 based rc 15.2

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-create/case-create.component.spec.ts
src/shared/components/case-editor/case-create/case-create.component.ts
src/shared/components/case-editor/case-progress/case-progress.component.spec.ts
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-viewer/printer/case-printer.component.ts

DO NOT MERGE UNTIL https://github.com/hmcts/ccd-data-store-api/pull/554 is merged.
https://tools.hmcts.net/jira/browse/RDM-4335
Rdm 4335 Implement and consume external POST Create Case endpoint in API v2
```
[x] Yes
[ ] No
```

Rdm 4335 Implement and consume external POST Create Case endpoint in API v2

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/complex/fields-filter.pipe.ts
src/shared/directives/substitutor/services/placeholder.service.spec.ts
src/shared/directives/substitutor/services/placeholder.service.ts
src/shared/services/fields/fields.utils.ts
src/shared/services/form/form-value.service.spec.ts
src/shared/services/form/form-value.service.ts

https://tools.hmcts.net/jira/browse/RDM-4837
Field interpolation syntax is displayed if the source field is NULL
```
[ ] Yes
[x] No
```

Rdm 4837 Field interpolation syntax is displayed if the source field is NULL

---

RELEASE-NOTES.md
package.json

RDM-5007: Updated release notes and toolkit version

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/domain/wizard-page-field.model.ts
src/shared/components/case-editor/services/wizard-page-field-to-case-field.mapper.spec.ts
src/shared/fixture/shared.test.fixture.ts

https://tools.hmcts.net/jira/browse/RDM-6887
Removed displayContext from WizardPageField
```
[ ] Yes
[X ] No
```

RDM-6887 Remove duplicate display context from data store endpoint

---

RELEASE-NOTES.md
package.json

Update final ccd version

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/fixed-list/fixed-list.module.ts
src/shared/components/palette/fixed-list/write-fixed-list-field.component.spec.ts
src/shared/components/palette/fixed-list/write-fixed-list-field.component.ts
src/shared/components/palette/fixed-list/write-fixed-list-field.html

https://tools.hmcts.net/jira/browse/RDM-7120
Change select element binding to [(ngModel)] and use [ngValue] instead of formControl and "value" attributes
```
[ ] Yes
[X ] No
```

RDM-7120: Regression: Unable to create Draft SDO in DEMO

---

.travis.yml
RELEASE-NOTES.md
package.json
src/index.ts
src/shared/services/index.ts
src/shared/services/url-transformation/index.ts
src/shared/services/url-transformation/url-transformation.service.spec.ts
src/shared/services/url-transformation/url-transformation.service.ts

https://tools.hmcts.net/jira/browse/RDM-7293
New service for transforming between internal/external URLs
```
[ ] Yes
[x] No
```

RDM-7293 - Introduce smart translation between internal and external URLs

---

RELEASE-NOTES.md
package.json
src/shared/components/dialogs/jurisdiction-shuttering-dialog/jurisdiction-shuttering-dialog.component.html
src/shared/components/dialogs/jurisdiction-shuttering-dialog/jurisdiction-shuttering-dialog.component.scss

https://tools.hmcts.net/jira/browse/RDM-7524
Wording changes for shuttering dialog
```
[ ] Yes
[X ] No
```

Rdm 7524: Wording Updates to CCD Shuttering and Redirection to Expert UI

---

src/shared/components/palette/utils/date.pipe.spec.ts

Fix DST issues with test

---

RELEASE-NOTES.md
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-1610
Changed package.json to point to npm instead of github for rx-polling
```
[ ] Yes
[x] No
```

EUI-1610 importing rx-polling from npmjs

---

src/shared/components/search-result/search-result.component.html
src/shared/components/search-result/search-result.component.scss

fixed the alignment

---

RELEASE-NOTES.md
package.json

prerelease prep

---

package.json
src/shared/components/search-result/search-result.component.spec.ts
src/shared/components/search-result/search-result.component.ts
yarn.lock

EU-2002-backward-preselect-cases

---

package.json
src/shared/components/case-list/case-list.component.html
src/shared/components/case-list/case-list.component.spec.ts
src/shared/components/case-list/case-list.component.ts
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-2115
Unit tests for Case List component, with selection enabled and disabled.
```
[ ] Yes
[x] No
```

Add unit tests

---

RELEASE-NOTES.md
package.json

https://tools.hmcts.net/jira/browse/EUI-2312
Update version and release notes for release `v2.64.19-security-fix`.
```
[ ] Yes
[x] No
```

Bump version number to 2.64.19-security-fix

---

RELEASE-NOTES.md
package.json
src/shared/components/search-result/search-result.component.spec.ts
src/shared/components/search-result/search-result.component.ts

Eui 2186 disable selection if no org policy

---

RELEASE-NOTES.md
package.json
src/shared/components/search-result/search-result.component.ts
yarn.lock

Added type to sort emitter

---

package.json
src/shared/components/search-result/search-result.component.html
src/shared/components/search-result/search-result.component.scss

EUI-2101-case-share-checkbox-fix

---

src/shared/components/case-list/case-list.component.html

remove role presentation due to accessibility issue

---

RELEASE-NOTES.md
package.json
src/shared/components/search-result/search-result.component.ts

EUI-2500 swapped .id with .type in case_type

---

RELEASE-NOTES.md
package.json
src/shared/components/search-result/search-result.component.spec.ts
src/shared/components/search-result/search-result.component.ts

EUI-2532 removed org-policy dependency when sharing a case

---

RELEASE-NOTES.md
package.json
src/shared/components/case-list/case-list.component.ts

reset selected cases on model change

---

RELEASE-NOTES.md
package.json
src/shared/components/case-list/case-list.component.ts

case-list-selection persist mutation free

---

RELEASE-NOTES.md
demo/src/app/app.config.ts
package.json
src/app.config.ts
src/index.ts
src/shared/services/index.ts
src/shared/services/organisation/index.ts
src/shared/services/organisation/organisation.service.ts

EUI-2229 cacheable org service

---

RELEASE-NOTES.md
package.json
src/shared/services/organisation/organisation.service.ts

EUI-2086-unhappy-path

---

RELEASE-NOTES.md
package.json
src/shared/services/search/search.service.spec.ts
src/shared/services/search/search.service.ts

https://tools.hmcts.net/jira/browse/EUI-2575
Change query parameter from `usecase` to `use_case`, following CCD change RDM-8932.
```
[ ] Yes
[x] No
```

EUI-2575: Update Internal Search API URL

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/history/case-history-viewer.module.ts

Eui 2649 case detail is broken

---

RELEASE-NOTES.md
package.json
src/shared/components/case-list/case-list.component.spec.ts
src/shared/components/case-list/case-list.component.ts

cases list date format

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
src/shared/services/fields/fields.purger.ts
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-2681
Do not set a field control's value to `null` if it corresponds to a complex `CaseField` type.
```
[ ] Yes
[x] No
```

EUI-2681: Fix retain hidden value support for complex field types

---

RELEASE-NOTES.md
package.json
src/shared/components/case-list/case-list.component.ts

check for selected cases

---

RELEASE-NOTES.md
package.json
src/shared/components/case-list/case-list.component.spec.ts
src/shared/components/case-list/case-list.component.ts

EUI-2740-fix-select-all-issue-on-MO

---

src/shared/components/case-list/case-list.component.ts
src/shared/services/fields/fields.purger.ts

2.64.47 case share hot fix retain case role

---

RELEASE-NOTES.md
package.json
src/shared/components/search-result/search-result.component.spec.ts
src/shared/components/search-result/search-result.component.ts
src/shared/domain/search/search-result-view-item.model.ts

2.64.48-sharable-case-hot-fix

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
src/shared/components/case-editor/case-edit/case-edit.component.spec.ts
src/shared/fixture/shared.test.fixture.ts
src/shared/services/fields/fields.purger.spec.ts
src/shared/services/fields/fields.purger.ts
src/shared/services/form/form-value.service.ts

https://tools.hmcts.net/jira/browse/EUI-2739
Functionality fixed for all field types, including Complex and Collection types.
```
[ ] Yes
[x] No
```

EUI-2739: Fix "retain hidden fields" functionality for all field types

---

.github/workflows/npmpublish.yml

add github actions

---

.github/workflows/npmpublish.yml

Change-NPM-token-key

---

RELEASE-NOTES.md
package.json
src/shared/components/case-viewer/case-viewer.component.ts
src/shared/components/palette/base-field/field-read.component.ts
src/shared/components/palette/history/event-log/event-log-table.component.spec.ts

https://tools.hmcts.net/jira/browse/EUI-2741
Performance issue which impacts Employment Tribunals usage of Manage Cases. Issue is clearly apparent when loading a case with large hearing and judgement collections.
```
[ ] Yes
[x] No
```

Move class-transformer call to improve performance

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/search-result/search-result.component.ts

https://tools.hmcts.net/jira/browse/EUI-2020
Focus order amends for accessibility
```
[ ] Yes
[x] No
```

Feature EUI-2020 focus order material

---

RELEASE-NOTES.md
package.json
src/shared/components/case-viewer/case-viewer.component.ts

Bug/e UI 3041 tab name replaceAll

---

src/shared/components/case-list/case-list.component.html
src/shared/components/case-list/case-list.component.spec.ts
src/shared/components/case-list/case-list.component.ts
src/shared/components/case-list/case-list.module.ts
src/shared/components/case-viewer/case-viewer.component.ts
src/shared/components/search-result/search-result.component.html
src/shared/components/search-result/search-result.component.spec.ts
src/shared/components/search-result/search-result.component.ts
src/shared/components/search-result/search-result.module.ts
src/shared/components/workbasket-filters/workbasket-filters.component.html
src/shared/components/workbasket-filters/workbasket-filters.component.spec.ts
src/shared/components/workbasket-filters/workbasket-filters.component.ts
src/shared/services/browser/browser.service.ts
src/shared/services/browser/index.ts
src/shared/services/index.ts

https://tools.hmcts.net/jira/browse/EUI-2989
https://tools.hmcts.net/jira/browse/EUI-2887
```
[ ] Yes
[ ] No
```

E UI 2989 keyboard not working with checkbox on firefox safari ie11

---

RELEASE-NOTES.md
package.json

updated the version name of the package

---

RELEASE-NOTES.md
demo/src/app/app.config.ts
package.json
src/app.config.ts
src/shared/components/case-editor/case-create/case-create.component.spec.ts
src/shared/components/case-editor/case-create/case-create.component.ts
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
src/shared/components/case-editor/case-edit/case-edit.component.ts
src/shared/components/case-editor/case-editor.module.ts
src/shared/components/case-editor/case-progress/case-progress.component.spec.ts
src/shared/components/case-editor/case-progress/case-progress.component.ts
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-editor/services/index.ts
src/shared/components/case-editor/services/work-allocation.service.spec.ts
src/shared/components/case-editor/services/work-allocation.service.ts
src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.spec.ts
src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.ts
src/shared/domain/index.ts
src/shared/domain/work-allocation/index.ts
src/shared/domain/work-allocation/task-search-parameter.model.ts

https://tools.hmcts.net/jira/browse/EUI-2986
Initial work (for discussion for the time being) on adding support for completing work allocation tasks when case events are completed.
Note: Not a breaking change as the additional parameters passed around are currently optional.
```
[ ] Yes
[x] No
```

EUI-2986: Task event completion

---

src/shared/components/case-editor/case-edit/case-edit.component.spec.ts
src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.spec.ts
src/shared/components/palette/address/write-address-field.component.spec.ts
src/shared/components/palette/base-field/abstract-field-read.component.ts
src/shared/components/palette/base-field/field-read.component.spec.ts
src/shared/components/palette/base-field/field-write.component.spec.ts
src/shared/components/palette/case-link/read-case-link-field.component.spec.ts
src/shared/components/palette/case-link/write-case-link-field.component.ts
src/shared/components/palette/collection/write-collection-field.component.spec.ts
src/shared/components/palette/collection/write-collection-field.component.ts
src/shared/components/palette/collection/write-collection-field.html
src/shared/components/palette/complex/write-complex-field.component.spec.ts
src/shared/components/palette/order-summary/write-order-summary-field.component.spec.ts
src/shared/components/palette/order-summary/write-order-summary-field.component.ts
src/shared/components/palette/organisation/write-organisation-field.component.ts
src/shared/components/palette/phone-uk/read-phone-uk-field.component.spec.ts
src/shared/components/palette/phone-uk/write-phone-uk-field.component.spec.ts
src/shared/components/palette/text-area/read-text-area-field.component.spec.ts
src/shared/components/palette/text-area/write-text-area-field.component.spec.ts
src/shared/components/palette/text/read-text-field.component.spec.ts
src/shared/components/palette/text/write-text-field.component.spec.ts
src/shared/components/palette/yes-no/read-yes-no-field.component.spec.ts
src/shared/components/palette/yes-no/write-yes-no-field.component.spec.ts

https://tools.hmcts.net/jira/browse/EUI-3168
Fixed a bunch of failing unit tests. There are still 34 failing, but that's down from 70. I think some of the remaining 34 can be ditched but that needs validating.
```
[ ] Yes
[x] No
```

EUI-3168: Fixing unit tests

---

src/shared/components/palette/collection/write-collection-field.component.spec.ts
src/shared/components/palette/collection/write-collection-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-3163
Horrible looking code to get the contents of a collection producing the right output for submission - fixed lists in particular.
```
[ ] Yes
[ ] No
[x] Hopefully not
```

EUI-3163: Fixed list not displaying within collection

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/cases.service.ts

This PR helps to feature toggle the Work Allocation services which are tied up in Case Service
```
[ ] Yes
[ X] No
```

work allocation task service is now feature toggled

---

src/shared/components/palette/address/write-address-field.component.ts
src/shared/components/palette/collection/write-collection-field.component.ts
src/shared/components/palette/complex/fields-filter.pipe.spec.ts
src/shared/components/palette/complex/fields-filter.pipe.ts
src/shared/components/palette/complex/write-complex-field.component.spec.ts
src/shared/components/palette/complex/write-complex-field.component.ts
src/shared/components/palette/complex/write-complex-field.html

https://tools.hmcts.net/jira/browse/EUI-3274
Fixed the show/hide functionality around addresses inside complex fields inside collections.
```
[ ] Yes
[x] No
```

EUI-3274: Addresses within complex fields within collections

---

RELEASE-NOTES.md
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/palette/case-link/write-case-link-field.html
src/shared/components/palette/collection/write-collection-field.component.ts
src/shared/components/palette/text-area/write-text-area-field.component.ts
src/shared/components/palette/text-area/write-text-area-field.html
src/shared/directives/conditional-show/conditional-show-form.directive.spec.ts
src/shared/directives/conditional-show/conditional-show-form.directive.ts

N/A
Merged master into this branch.
```
[ ] Yes
[ ] No
[x] Who knows?
```

Merge from master

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/history/event-log/event-log-table.scss

https://tools.hmcts.net/jira/browse/EUI-2030
Change selected table row background colour for accessibility (AA)
```
[ ] Yes
[x] No
```

Change table row background colour for accessibility (AA)

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.ts
src/shared/components/palette/document/write-document-field.component.spec.ts
src/shared/components/palette/document/write-document-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-2243
Fix upload replacement document issue
```
[ ] Yes
[x] No
```

EUI-2243 upload document issue

---

RELEASE-NOTES.md
package.json

2.70.0-fix-alert-service

---

RELEASE-NOTES.md
package.json
src/shared/services/form/form-value.service.ts

https://tools.hmcts.net/jira/browse/EUI-3398
Remove labels that have an empty string value, as well as those that are null
```
[ ] Yes
[ x] No
```

Fix EUI-3398 - submitting labels with empty string values

---

src/shared/components/workbasket-filters/workbasket-filters.component.ts

https://tools.hmcts.net/jira/browse/EUI-2569
https://tools.hmcts.net/jira/browse/EUI-2646
https://tools.hmcts.net/jira/browse/EUI-3024
Fixed a linting error on a line that was too long.
```
[ ] Yes
[x] No
```

Tech debt: Linting error

---

RELEASE-NOTES.md
demo/src/app/app.config.ts
package.json
src/app.config.ts
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-editor/services/work-allocation.service.spec.ts
src/shared/components/case-editor/services/work-allocation.service.ts
src/shared/domain/user/user-details.model.ts
src/shared/domain/user/user-info.model.ts
tsconfig.json

https://tools.hmcts.net/jira/browse/EUI-3229
(which follows on from related changes in https://tools.hmcts.net/jira/browse/EUI-3232)
Improving task event completion
```
[] Yes
[ x ] No
```

E UI 3229 task completion iac role

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
src/shared/services/form/form-value.service.ts

https://tools.hmcts.net/jira/browse/EUI-3403 (this part is in the comments)
Don't submit empty documents as the backend throws an exception.
```
[ ] Yes
[x] No
```

EUI-3403: Do not submit empty documents

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/base-field/field-read.component.ts
src/shared/components/palette/base-field/field-write.component.ts
src/shared/domain/definition/case-field.model.ts

https://tools.hmcts.net/jira/browse/EUI-3045
Fixed an issue where nulls were not being properly handled for Dynamic List values.
```
[ ] Yes
[x] No
```

EUI-3045: Dynamic list handle null value

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/complex/fields-filter.pipe.ts

https://tools.hmcts.net/jira/browse/EUI-3452
Fixed an issue with show/hide not working correctly for complex types on the Check Your Answers page.
```
[ ] Yes
[x] No
```

EUI-3452: Check your answers show/hide not working

---

RELEASE-NOTES.md
package.json

https://tools.hmcts.net/jira/browse/EUI-3494
https://tools.hmcts.net/jira/browse/EUI-3495
Release of v2.72.9-fix-case-submission.
```
[ ] Yes
[x] No
```

v2.72.9-fix-case-submission

---

package.json
src/shared/components/search-result/search-result.component.html
src/shared/components/search-result/search-result.component.scss

https://tools.hmcts.net/jira/browse/EUI-2031
by accident, it also resolves: https://tools.hmcts.net/jira/browse/EUI-2033
Changed link text so it matches GDS style and satisfies WCAG AA
```
[ ] Yes
[X] No
```

added focus link styling for table row anchor links

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/dynamic-list/write-dynamic-list-field.component.spec.ts
src/shared/components/palette/dynamic-list/write-dynamic-list-field.component.ts
src/shared/components/palette/dynamic-list/write-dynamic-list-field.html
src/shared/components/palette/fixed-list/write-fixed-list-field.component.spec.ts
src/shared/components/palette/fixed-list/write-fixed-list-field.component.ts
src/shared/components/palette/fixed-list/write-fixed-list-field.html

https://tools.hmcts.net/jira/browse/EUI-3410
Remove ngModel from write-dynamic-list-field and write-fixed-list-field
```
[ ] Yes
[x] No
```

Remove ngModel from fields and fix tests

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.html
src/shared/components/case-editor/case-edit-submit/case-edit-submit.html
src/shared/components/case-header/case-header.component.ts
src/shared/components/case-header/case-header.html

https://tools.hmcts.net/jira/browse/EUI-3506
Non-descriptive heading amends for accessibility (AA)
```
[ ] Yes
[x] No
```

Non-descriptive heading amends for accessibility (AA)

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/dynamic-list/write-dynamic-list-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-3577
Fixed regression bugs
```
[ ] Yes
[x] No
```

Bug/e UI 3577 regressions aa

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-editor/services/work-allocation.service.spec.ts
src/shared/components/case-editor/services/work-allocation.service.ts
src/shared/domain/work-allocation/task-search-parameter.model.ts

https://tools.hmcts.net/jira/browse/EUI-3548
Integrating with WA/ EXUInode api
```
[ ] Yes
[X] No
```

Task event completion - Integration changes

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-editor/services/work-allocation.service.spec.ts
src/shared/components/case-editor/services/work-allocation.service.ts
src/shared/domain/work-allocation/task-search-parameter.model.ts

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/EUI-3548
Change description
Integrating with WA/ EXUInode api
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No
Original PR to master is https://github.com/hmcts/ccd-case-ui-toolkit/pull/715

Feature toggle work allocation and change some parameters

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/organisation/write-organisation-field.component.spec.ts
src/shared/components/palette/organisation/write-organisation-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-3674
When organisation is not selected and if it's set MANDATORY in CCD config, the validation should be failed.
```
[ ] Yes
[x] No
```

EUI-3674-mandatory-organisation

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/complex/ccd-read-fields-filter.pipe.spec.ts
src/shared/components/palette/complex/ccd-read-fields-filter.pipe.ts

https://tools.hmcts.net/jira/browse/EUI-3797 ✅ `DONE`
Fix to ensure the contents of the Payment History tab are shown.
```
[ ] Yes
[x] No
```

EUI-3797: Missing payments tab

---

RELEASE-NOTES.md
package.json
src/shared/services/activity/activity.polling.service.ts

https://tools.hmcts.net/jira/browse/EUI-3638
https://tools.hmcts.net/jira/browse/EUI-2925
Reduced activity post calls to 5 seconds.
```
[ ] Yes
[👋 Hello Paul G!] No
```

Bug/e UI 3638 activity tracker aa

---

RELEASE-NOTES.md
src/shared/components/palette/collection/write-collection-field.component.spec.ts
src/shared/components/palette/collection/write-collection-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-3505
Reverted PR merge
```
[ ] Yes
[x] No
```

Revert "Bug/e UI 3505 crud 2 aa (#763)"

---

package.json

Nothing changes bump up to v3.0.2 for LIVE release
```
[ ] Yes
[x] No
```

bump up to version v3.0.2

---

RELEASE-NOTES.md
package.json
src/shared/components/search-filters/search-filters.component.html
src/shared/components/search-filters/search-filters.component.spec.ts
src/shared/components/search-filters/search-filters.component.ts
src/shared/components/search-filters/search-filters.module.ts
src/shared/components/workbasket-filters/workbasket-filters.component.html
src/shared/components/workbasket-filters/workbasket-filters.component.spec.ts
src/shared/components/workbasket-filters/workbasket-filters.component.ts
src/shared/components/workbasket-filters/workbasket-filters.module.ts

https://tools.hmcts.net/jira/browse/EUI-3538
Add ccdConditionalShowForm to both the Search and Workbasket filters
```
[ ] Yes
[x] No
```

Add ccdConditionalShowForm to filters

---

src/case-ui-toolkit.module.ts
src/index.ts
src/shared/components/index.ts
src/shared/components/pagination/index.ts
src/shared/components/pagination/pagination.module.ts

https://tools.hmcts.net/jira/browse/EUI-4013
Exported the pagination component for external consumption
```
[ ] Yes
[x] No
```

exported the pagination component for external consumption

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-editor.module.ts
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-list-filters/case-list-filters.module.ts
src/shared/services/index.ts
src/shared/services/session/index.ts
src/shared/services/session/session-storage-service.spec.ts
src/shared/services/session/session-storage.service.ts

https://tools.hmcts.net/jira/browse/EUI-4077
Checking for pui-case-manager role to determine whether searchForCompletable needs to be called
```
[ ] Yes
[ x ] No
```

Make pcm role check

---

RELEASE-NOTES.md
package.json
src/shared/components/activity/activity.module.ts
src/shared/services/activity/activity.polling.service.ts
src/shared/services/activity/activity.service.spec.ts
src/shared/services/activity/activity.service.ts
src/shared/services/loading/loading.service.spec.ts
src/shared/services/session/session-storage-service.spec.ts
src/shared/services/session/session-storage.service.ts

Activity Tracker changes which are missing in the master. 
```
[ ] Yes
[X] No
```

Activity tracker changes ud

---

sonar-project.properties

None.
Test of sonar-project.properties changes.
```
[ ] Yes
[x] No
```

Remove comment from properties file

---

sonar-project.properties

None.
Merging latest `sonar-project.properties` file.
```
[ ] Yes
[x] No
```

Bug e UI 2022 validation error fix 2 sonar

---

RELEASE-NOTES.md
package.json
src/case-ui-toolkit.module.ts
src/index.ts
src/shared/components/index.ts
src/shared/components/pagination/index.ts
src/shared/components/pagination/pagination.component.html
src/shared/components/pagination/pagination.component.scss
src/shared/components/pagination/pagination.component.spec.ts
src/shared/components/pagination/pagination.component.ts
src/shared/components/pagination/pagination.module.ts
src/shared/components/pagination/testing/testing-helpers.ts
src/shared/services/loading/loading.service.spec.ts

https://tools.hmcts.net/jira/browse/EUI-4013
https://tools.hmcts.net/jira/browse/EUI-4024
https://tools.hmcts.net/jira/browse/EUI-4029
https://tools.hmcts.net/jira/browse/EUI-4031
This is a priority feature release of Pagination in absence of https://tools.hmcts.net/jira/browse/EUI-4020 
```
[ ] Yes
[X] No
```

Priority release - Pagination feature

---

package.json
src/shared/directives/conditional-show/domain/conditional-show.model.ts
src/shared/domain/definition/case-field.model.ts

https://tools.hmcts.net/jira/browse/CCD-1047
Fix Advisory - 1674 in case management web
```
[ ] Yes
[x] No
```

Ccd 1047 isEmpty changes

---

package.json

https://tools.hmcts.net/jira/browse/CCD-1047
Fix Advisory - 1674 in case management web
```
[ ] Yes
[x] No
```

Rdm 8661 money gbp e UI ccd

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/datetime-picker/datetime-picker-component.spec.ts
src/shared/components/palette/datetime-picker/datetime-picker.component.html
src/shared/components/palette/datetime-picker/datetime-picker.component.ts
src/shared/domain/definition/case-field.model.ts
src/shared/services/case-fields/format-translator.service.spec.ts
src/shared/services/case-fields/format-translator.service.ts
src/shared/services/form/form-validators.service.ts
src/shared/services/loading/loading.service.spec.ts

https://tools.hmcts.net/jira/browse/EUI-4118
Implementing validation for required, minimum and maximum date errors as well as improving validation for invalid dates
```
[ ] Yes
[ x ] No
```

Bugfix/e UI 4118 mandatory datetime picker

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/history/event-log/event-log-details.component.html
src/shared/components/palette/history/event-log/event-log-details.component.spec.ts
src/shared/components/palette/history/event-log/event-log-table.component.html
src/shared/services/loading/loading.service.spec.ts

https://tools.hmcts.net/jira/browse/EUI-4095
Services have requested timestamp for events be in local time
```
[ ] Yes
[ x ] No
```

EUI-4095 - Apply fix

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/collection/write-collection-field.html
src/shared/components/palette/complex/read-complex-field-table.html
src/shared/components/palette/utils/first-error.pipe.ts
src/shared/directives/conditional-show/domain/conditional-show.model.ts

https://tools.hmcts.net/jira/browse/EUI-2022
Handling validation error for complex type fields
```
[ ] Yes
[x] No
```

handling validations for complex field type

---

src/shared/directives/substitutor/label-substitutor.directive.spec.ts
src/shared/directives/substitutor/services/placeholder.service.spec.ts
src/shared/services/fields/fields.utils.spec.ts
src/shared/services/form/form-value.service.spec.ts
src/shared/services/form/form-value.service.ts

https://tools.hmcts.net/jira/browse/EUI-4244
Made a "minor tweak" prior to committing and pushing. The global search didn't bring back anything suspicious... but I was excluding `.spec.ts` files. Like an idiot. 🤦‍♂️ 
```
[ ] Yes
[x] No
```

EUI-4244: The "never forget to run tests and lint after a minor tweak" PR

---

package.json

Update version to 4.1.6

---

package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/palette/complex/read-complex-field.component.spec.ts
src/shared/components/palette/complex/read-complex-field.component.ts
src/shared/components/palette/dynamic-list/dynamic-list.pipe.ts
src/shared/components/palette/dynamic-radio-list/dynamic-radio-list.module.ts
src/shared/components/palette/dynamic-radio-list/dynamic-radio-list.pipe.spec.ts
src/shared/components/palette/dynamic-radio-list/dynamic-radio-list.pipe.ts
src/shared/components/palette/dynamic-radio-list/index.ts
src/shared/components/palette/dynamic-radio-list/read-dynamic-radio-list-field.component.spec.ts
src/shared/components/palette/dynamic-radio-list/read-dynamic-radio-list-field.component.ts
src/shared/components/palette/dynamic-radio-list/write-dynamic-radio-list-field.component.spec.ts
src/shared/components/palette/dynamic-radio-list/write-dynamic-radio-list-field.component.ts
src/shared/components/palette/dynamic-radio-list/write-dynamic-radio-list-field.html
src/shared/components/palette/palette.module.ts
src/shared/components/palette/palette.service.ts
src/shared/domain/definition/case-field.model.ts
src/shared/domain/definition/field-type-enum.model.ts
src/shared/services/form/field-type-sanitiser.ts
tsconfig-aot.json
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-2829
Rebased Phil's PR onto release-4.2.0 and fixed conflicts/issues etc
```
[ ] Yes
[x] No
```

Feature/e UI 2829 dynamic radio list phillip whitaker 2

---

src/shared/components/palette/base-field/abstract-field-write.component.ts
src/shared/components/palette/base-field/field-write.component.ts
src/shared/components/palette/collection/write-collection-field.component.spec.ts
src/shared/components/palette/collection/write-collection-field.component.ts
src/shared/components/palette/collection/write-collection-field.html
src/shared/components/palette/complex/write-complex-field.component.spec.ts
src/shared/components/palette/complex/write-complex-field.html
src/shared/components/workbasket-filters/workbasket-filters.component.html
src/shared/domain/definition/case-field.model.ts
src/shared/services/request/request.options.builder.ts

N/A
Rebased from release-4.2.0
```
[ ] Yes
[x] No
```

Bug/e UI 3621 collection search filter 2 aa

---

RELEASE-NOTES.md
package.json
src/app.config.ts
src/shared/components/palette/datetime-picker/datetime-picker-component.spec.ts
src/shared/components/palette/document/write-document-field.component.spec.ts
src/shared/components/palette/document/write-document-field.component.ts
src/shared/domain/document/document-data.model.ts
src/shared/services/document-management/document-management.service.spec.ts
src/shared/services/document-management/document-management.service.ts

https://tools.hmcts.net/jira/browse/EUI-3425
https://tools.hmcts.net/jira/browse/EUI-3426
Changed the upload process based on the secureMode configuration
```
[ ] Yes
[x] No
```

EUI-3425 secure docstore upload

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/document/write-document-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-3425
Added check for case type and jurisdiction
```
[ ] Yes
[x] No
```

Hotfix/e UI 3425 secure upload

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-editor/domain/wizard.model.spec.ts
src/shared/components/case-editor/domain/wizard.model.ts

https://tools.hmcts.net/jira/browse/EUI-4364
Values disappearing after mid event callback when modifying case data through amend application event
```
[ ] Yes
[x] No
```

EUI-4364-value-disappearing

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-confirm/case-edit-confirm.html
src/shared/components/case-editor/case-edit-page/case-edit-page.html
src/shared/components/case-editor/case-edit-submit/case-edit-submit.html
src/shared/pipes/case-title/ccd-case-title.pipe.spec.ts
src/shared/pipes/case-title/ccd-case-title.pipe.ts

https://tools.hmcts.net/jira/browse/EUI-4415
Label not rendering 
```
[ ] Yes
[x] No
```

EUI-4415 Label not rendering

---

RELEASE-NOTES.md
package.json
src/components/banners/alert/alert.component.html
src/components/banners/alert/alert.component.ts
src/shared/components/case-viewer/case-challenged-access-request/case-challenged-access-request.component.html
src/shared/components/case-viewer/case-challenged-access-request/case-challenged-access-request.component.ts
src/shared/components/case-viewer/case-challenged-access-request/case-challenged-access-view.component.spec.ts
src/shared/components/case-viewer/case-challenged-access-request/index.ts
src/shared/components/case-viewer/case-challenged-access-request/models/case-challenged-access-request.enum.ts
src/shared/components/case-viewer/case-challenged-access-request/models/index.ts
src/shared/components/case-viewer/case-viewer.module.ts
src/shared/components/case-viewer/index.ts
src/shared/components/case-viewer/viewer.routing.ts
src/shared/components/error-message/error-message.component.html
src/shared/components/error-message/error-message.component.ts
src/shared/components/error-message/index.ts
src/shared/components/index.ts
src/shared/domain/error-message.model.ts
src/shared/domain/index.ts

https://tools.hmcts.net/jira/browse/EUI-3473
Implementation of display-only User Story.
```
[ ] Yes
[x] No
```

EUI-3473: Challenged Access Request screen for Case Access Management

---

src/shared/components/case-viewer/case-challenged-access-request/case-challenged-access-view.component.spec.ts

None.
Correction to change `fdescribe` to `describe`, to allow all other tests to run.
```
[ ] Yes
[x] No
```

Change fdescribe to describe, to allow all other tests to run

---

package.json
src/shared/components/workbasket-filters/workbasket-filters.component.spec.ts
src/shared/components/workbasket-filters/workbasket-filters.component.ts

https://tools.hmcts.net/jira/browse/EUI-4297
Case search list not updated when changing Region or FRC details
```
[ ] Yes
[X] No
```

EUI-4297 Search list not updated when changing Region or FRC

---

RELEASE-NOTES.md
src/shared/components/case-editor/case-edit-confirm/case-edit-confirm.html
src/shared/components/case-editor/case-edit-page/case-edit-page.html
src/shared/components/case-editor/case-edit-submit/case-edit-submit.html
src/shared/pipes/case-title/ccd-case-title.pipe.spec.ts
src/shared/pipes/case-title/ccd-case-title.pipe.ts
src/shared/services/search/search.service.spec.ts

https://tools.hmcts.net/jira/browse/EUI-4415
Label not rendered properly
```
[ ] Yes
[x] No
```

EUI-4415-Label not rendered properly

---

RELEASE-NOTES.md
package.json
src/shared/components/activity/activity.component.ts
src/shared/components/case-editor/case-edit-form/case-edit-form.component.ts
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
src/shared/components/case-history/case-history.component.ts
src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.ts
src/shared/components/case-viewer/case-view/case-view.component.ts
src/shared/components/case-viewer/case-viewer.component.ts
src/shared/components/case-viewer/printer/case-printer.component.ts
src/shared/components/error/callback-errors.component.ts
src/shared/components/palette/collection/write-collection-field.component.ts
src/shared/components/palette/document/read-document-field.component.ts
src/shared/components/palette/document/write-document-field.component.ts
src/shared/services/activity/activity.service.ts
src/shared/services/document-management/document-management.service.spec.ts
src/shared/services/document-management/document-management.service.ts
tsconfig-aot.json

https://tools.hmcts.net/jira/browse/EUI-4210
Automated test fails
```
[ ] Yes
[x] No
```

EUI-4210-from-release-4.3.0

---

package.json
src/shared/directives/conditional-show/domain/conditional-show.model.spec.ts
src/shared/directives/conditional-show/domain/conditional-show.model.ts

https://tools.hmcts.net/jira/browse/EUI-4567
Nested fields inside a collection not displayed
```
[ ] Yes
[ x ] No
```

EUI-4567 Nested fields collection

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/complex/cdd-page-fields.pipe.ts

https://tools.hmcts.net/jira/browse/EUI-4412
Field order on the CYA page changes
```
[ ] Yes
[x] No
```

EUI-4412-Field order on the CYA page

---

package.json
src/app-config.mock.ts
src/app.config.ts
src/shared/components/case-viewer/case-review-specific-access-request/case-review-specific-access-request.component.html
src/shared/components/case-viewer/case-review-specific-access-request/case-review-specific-access-request.component.scss
src/shared/components/case-viewer/case-review-specific-access-request/case-review-specific-access-request.component.spec.ts
src/shared/components/case-viewer/case-review-specific-access-request/case-review-specific-access-request.component.ts
src/shared/components/case-viewer/case-review-specific-access-request/index.ts
src/shared/components/case-viewer/case-review-specific-access-request/models/case-review-specific-access-request.enum.ts
src/shared/components/case-viewer/case-review-specific-access-request/models/index.ts
src/shared/components/case-viewer/case-viewer.module.ts
src/shared/components/case-viewer/viewer.routing.ts
src/shared/components/palette/history/event-log/event-log-details.component.spec.ts
src/shared/domain/case-view/index.ts
src/shared/domain/case-view/review-specific-access-request.model.ts

https://tools.hmcts.net/jira/browse/EUI-3478
review specific access request for case 
```
[ ] Yes
[x] No
```

Feature/e UI 3478 review specific access request page

---

package.json
src/shared/services/form/form-value.service.spec.ts
src/shared/services/form/form-value.service.ts

https://tools.hmcts.net/jira/browse/EUI-4703
Clerks are unable to update a case when they choose not to attend the hearing
```
[ ] Yes
[ x ] No
```

EUI-4703 hearing date fix

---

package.json
src/shared/components/case-viewer/case-review-specific-access-reject/case-review-specific-access-reject.component.html
src/shared/components/case-viewer/case-review-specific-access-reject/case-review-specific-access-reject.component.spec.ts
src/shared/components/case-viewer/case-review-specific-access-reject/case-review-specific-access-reject.component.ts
src/shared/components/case-viewer/case-review-specific-access-reject/index.ts
src/shared/components/case-viewer/case-review-specific-access-request/case-review-specific-access-request.component.spec.ts
src/shared/components/case-viewer/case-review-specific-access-request/case-review-specific-access-request.component.ts
src/shared/components/case-viewer/case-viewer.module.ts
src/shared/components/case-viewer/viewer.routing.ts

https://tools.hmcts.net/jira/browse/EUI-3503
reject case for review specific access request 
```
[ ] Yes
[x] No
```

Feature/e UI 3503 reject specific access request

---

src/shared/components/case-editor/case-access-utils/index.spec.ts
src/shared/components/case-editor/case-access-utils/index.ts
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-viewer/case-specific-access-request/case-specific-access-request.component.spec.ts
src/shared/components/case-viewer/case-specific-access-request/case-specific-access-request.component.ts
src/shared/domain/case-view/index.ts
src/shared/domain/case-view/specific-access-request.model.ts

https://tools.hmcts.net/jira/browse/EUI-4195
Specific request
```
[ ] Yes
[x] No
```

Feature/e UI 4195 specific access node aa

---

package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts

https://tools.hmcts.net/jira/browse/EUI-4839
Spinner fix
```
[ ] Yes
[ x ] No
```

Bug/e UI 4839

---

package.json

Prepare toolkit for hearing release
Prepare toolkit for hearing release
```
[ ] Yes
[x] No
```

4.9.0-hearing-rc1

---

package.json
src/shared/components/palette/payment/case-payment-history-viewer-field.component.spec.ts
src/shared/components/palette/payment/case-payment-history-viewer-field.component.ts
src/shared/components/palette/payment/case-payment-history-viewer-field.html
yarn.lock

ccpay component version downgrade
```
[ ] Yes
[x] No
```

ccpay version change

---

src/shared/components/event-management/components/no-tasks-available/no-tasks-available.component.spec.ts
src/shared/components/event-management/components/no-tasks-available/no-tasks-available.component.ts
src/shared/components/event-management/event-guard/event-start.guard.spec.ts
src/shared/components/event-management/event-guard/event-start.guard.ts
src/shared/components/event-management/event-management.module.ts
src/shared/components/event-management/event-start/event-start.component.spec.ts
src/shared/components/event-management/event-start/event-start.component.ts
src/shared/components/event-management/index.ts
src/shared/components/event-management/models/index.ts
src/shared/components/event-management/models/state-machine-context.model.ts
src/shared/components/event-management/services/event-state-machine.service.spec.ts
src/shared/components/event-management/services/event-state-machine.service.ts
src/shared/components/event-management/services/index.ts

https://tools.hmcts.net/jira/browse/EUI-4527
Create error component no task found
```
[ ] Yes
[X] No
```

EUI-4527 Create error component no task found

---

src/shared/components/case-viewer/viewer.routing.ts
src/shared/components/event-management/components/task-assigned/task-assigned.component.spec.ts
src/shared/components/event-management/components/task-assigned/task-assigned.component.ts
src/shared/components/event-management/components/task-unassigned/task-unassigned.component.html
src/shared/components/event-management/components/task-unassigned/task-unassigned.component.spec.ts
src/shared/components/event-management/components/task-unassigned/task-unassigned.component.ts
src/shared/components/event-management/event-management.module.ts
src/shared/components/event-management/event-start/event-start.component.spec.ts
src/shared/components/event-management/event-start/event-start.component.ts
src/shared/components/event-management/index.ts
src/shared/components/event-management/models/state-machine-context.model.ts
src/shared/components/event-management/services/event-state-machine.service.spec.ts
src/shared/components/event-management/services/event-state-machine.service.ts

https://tools.hmcts.net/jira/browse/EUI-4099
Task completion - Task check at start of event - 1 task only associated with Event
```
[ ] Yes
[X] No
```

EUI-4099 Task check at start one task only

---

RELEASE-NOTES.md
package.json
src/shared/components/event-management/components/multiple-tasks-exist/multiple-tasks-exist.component.spec.ts
src/shared/components/event-management/components/multiple-tasks-exist/multiple-tasks-exist.component.ts
src/shared/components/event-management/event-guard/event-start.guard.ts
src/shared/components/event-management/event-start/event-start.component.spec.ts
src/shared/components/event-management/event-start/event-start.component.ts
src/shared/components/event-management/models/event-states-enum.model.ts
src/shared/components/event-management/models/state-machine-context.model.ts
src/shared/components/event-management/services/event-state-machine.service.spec.ts
src/shared/components/event-management/services/event-state-machine.service.ts

https://tools.hmcts.net/jira/browse/EUI-4100
Task completion - Task check at start of event - >1 tasks associated with Event
```
[ ] Yes
[X] No
```

EUI-4100 Task check at start multiple tasks

---

RELEASE-NOTES.md
package.json
src/shared/components/event-management/services/event-state-machine.service.spec.ts
src/shared/components/event-management/services/event-state-machine.service.ts

https://tools.hmcts.net/jira/browse/EUI-4100
Task completion - Task check at start of event - >1 tasks associated with Event additional changes
```
[ ] Yes
[X] No
```

EUI-4100 Task check at start multiple tasks code changes

---

package.json
src/shared/components/palette/case-link/write-case-link-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-4329
validation fails for bulk cases
```
[ ] Yes
[x] No
```

validation added

---

package.json
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts

https://tools.hmcts.net/jira/browse/EUI-4568
prevent resubmission of claim after clicking back button
```
[ ] Yes
[x] No
```

EUI-4568-resubmit-claim

---

package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-viewer/case-viewer.component.html
src/shared/components/palette/complex/ccd-read-fields-filter.pipe.ts

removed duplicate selector and updated version

---

package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-viewer/case-viewer.component.html
src/shared/components/palette/complex/ccd-read-fields-filter.pipe.ts

Reverts hmcts/ccd-case-ui-toolkit#992

Revert "removed duplicate selector and updated version"

---

package.json
src/shared/components/case-editor/services/cases.service.spec.ts
src/shared/components/case-header/case-header.component.ts
src/shared/components/case-header/case-header.html
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
src/shared/components/palette/payment/case-payment-history-viewer-field.component.spec.ts
src/shared/components/palette/payment/case-payment-history-viewer-field.component.ts
src/shared/components/palette/payment/case-payment-history-viewer-field.html
src/shared/components/workbasket-filters/workbasket-filters.component.ts
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-5149
Revert commits from toolkit master for refund release failure.
```
[ ] Yes
[x] No
```

Revert to 4.8.3 no refunds rc.1

---

demo/src/app/app.module.ts
demo/src/app/case-progress-consumer.component.html
demo/stubs/api.json
src/case-ui-toolkit.module.ts
src/shared/components/palette/case-flag/enums/index.ts
src/shared/components/palette/case-flag/enums/write-case-flag-field.enum.ts
src/shared/components/palette/case-flag/index.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.html
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts
src/shared/components/palette/index.ts
src/shared/components/palette/palette.module.ts
src/shared/components/palette/palette.service.spec.ts
src/shared/components/palette/palette.service.ts
src/shared/domain/definition/field-type-enum.model.ts

[EUI-4921](https://tools.hmcts.net/jira/browse/EUI-4921)
Initial base implementation to get component interaction with Case Event flow working.
```
[ ] Yes
[x] No
```

EUI-4921: Implement writable Case Flag field

---

src/shared/components/case-viewer/services/case.resolver.ts
src/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.ts
src/shared/components/palette/case-flag/domain/case-flag.model.ts
src/shared/components/palette/case-flag/enums/case-flag-status.enum.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts
src/shared/components/palette/palette.service.spec.ts
src/shared/components/palette/palette.service.ts
src/shared/domain/case-view/case-view.model.ts
src/shared/domain/definition/field-type-enum.model.ts
src/shared/services/fields/fields.utils.ts

[EUI-5257](https://tools.hmcts.net/jira/browse/EUI-5257)
Extract all flags-related data from the `CaseEventTrigger` object in the snapshot data and map to a collection of `Flags` objects and their `FlagDetail` children.
```
[ ] Yes
[x] No
```

EUI-5257: Extract Case Flags data for use by WriteCaseFlagFieldComponent

---

package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts

https://tools.hmcts.net/jira/browse/EUI-4429
Throws js error while amend case
```
[ ] Yes
[x] No
```

EUI-4429-error-while-amend-case

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-submit/case-edit-submit.html

https://tools.hmcts.net/jira/browse/EUI-5305
- Added `aria-label` attribute to for change link
- Update package.json version and release notes
```
[ ] Yes
[X] No
```

EUI 5305 - change link accessibility update

---

package.json
src/shared/services/fields/fields.utils.spec.ts
src/shared/services/fields/fields.utils.ts

https://tools.hmcts.net/jira/browse/EUI-5128
handling collecton of dynamiclist values
```
[ ] Yes
[x] No
```

fixed collection of dynamic list issue

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/base-field/field-write.component.spec.ts
src/shared/components/palette/base-field/field-write.component.ts
src/shared/components/palette/case-flag/case-flag.module.ts
src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.html
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.html
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.ts
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.html
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts
src/shared/services/fields/fields.utils.spec.ts
src/shared/services/fields/fields.utils.ts

[EUI-5374](https://tools.hmcts.net/jira/browse/EUI-5374)
[EUI-5372](https://tools.hmcts.net/jira/browse/EUI-5372)
Fix error message text on clicking "Continue" when creating a Case Flag; fix incorrect handling of display of Case Event flow error message.
```
[ ] Yes
[x] No
```

EUI-5374/EUI-5372: Create Case Flag - Case Event flow error message handling fixes

---

src/shared/components/palette/complex/ccd-read-fields-filter.pipe.ts

Refactor how we filter out nullable fields

---

package.json
src/shared/components/palette/complex/read-complex-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-3943
Reset the `Casefield.display_context_parameter` prop to default if the value is undefined
```
[ ] Yes
[ x] No
```

display the table collection values

---

package.json
src/shared/components/markdown/markdown.component.ts
src/shared/components/markdown/markdown.html

https://tools.hmcts.net/jira/browse/EUI-5632
Mark down component routerLink instead of href
```
[ ] Yes
[X] No
```

introduce onMarkdownClick optional input paramters

---

RELEASE-NOTES.md
demo/src/app/app.config.ts
package.json
src/app-config.mock.ts
src/app.config.ts
src/shared/components/palette/case-flag/case-flag.module.ts
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.html
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
src/shared/components/palette/case-flag/domain/case-flag.model.ts
src/shared/domain/case-flag/flag-type.model.ts
src/shared/domain/case-flag/hmcts-service-detail.model.ts
src/shared/domain/case-flag/index.ts
src/shared/services/case-flag/case-flag-refdata.service.spec.ts
src/shared/services/case-flag/case-flag-refdata.service.ts
src/shared/services/case-flag/index.ts
src/shared/services/case-flag/refdata-case-flag-type.enum.ts
src/shared/services/index.ts

[EUI-5495](https://tools.hmcts.net/jira/browse/EUI-5495)
[EUI-4845](https://tools.hmcts.net/jira/browse/EUI-4845)
Integrate "select flag type" step of case flag creation with Reference Data Common API, to retrieve list of flag types.
```
[ ] Yes
[x] No
```

EUI-5495/EUI-4845: Create Case Flag - Reference Data integration

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.html
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
src/shared/components/palette/case-flag/domain/case-flag-state.model.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.html
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts
src/shared/services/case-flag/index.ts

[EUI-5351](https://tools.hmcts.net/jira/browse/EUI-5351)
Support for display and selection of multi-level flag types at "Select flag type" step.
```
[ ] Yes
[x] No
```

EUI-5351: Create Case Flag - multi-level flag types

---

package.json
src/shared/components/case-viewer/services/case.resolver.ts

https://tools.hmcts.net/jira/browse/EUI-5634
Case Details loaded each time you click on a tab
```
[ ] Yes
[x] No
```

EUI-5634-Case Details loaded each time you click on a tab

---

package.json
src/shared/components/case-viewer/services/case.resolver.ts

https://tools.hmcts.net/jira/browse/EUI-5633
https://tools.hmcts.net/jira/browse/EUI-5634
https://tools.hmcts.net/jira/browse/EUI-3650
https://tools.hmcts.net/jira/browse/EUI-4746
https://tools.hmcts.net/jira/browse/EUI-4785
https://tools.hmcts.net/jira/browse/EUI-4860
MC Release-6.50
```
[ ] Yes
[x] No
```

mc-release-6.5.0

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/complex/read-complex-field-collection-table.html

https://tools.hmcts.net/jira/browse/EUI-5682
Added null coalescence to the complex table collection view 
```
[ ] Yes
[x] No
```

Added null coalesence for table values

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.html
src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.spec.ts
src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.ts
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts
src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
src/shared/components/palette/case-flag/domain/case-flag-state.model.ts
src/shared/components/palette/case-flag/enums/case-flag-wizard-step-title.enum.ts
src/shared/components/palette/case-flag/enums/search-language-interpreter-step.enum.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.html
src/shared/components/palette/case-flag/write-case-flag-field.component.ts

[EUI-5772](https://tools.hmcts.net/jira/browse/EUI-5772)
Display page title and hint text variation when selected language flag type is sign language.
```
[ ] Yes
[x] No
```

EUI-5772: Create Case Flag - "Search for a sign language interpreter" text variation

---

package.json
src/shared/components/case-editor/services/cases.service.ts
src/shared/domain/user/user-info.model.ts

openId-fix
```
[ ] Yes
[X] No
```

openId-fix

---

package.json
src/shared/components/palette/case-link/components/link-cases/link-cases.component.html
src/shared/components/palette/case-link/components/link-cases/link-cases.component.spec.ts
src/shared/components/palette/case-link/components/link-cases/link-cases.component.ts
src/shared/components/palette/case-link/enums/write-linked-cases-field.enum.ts
src/shared/components/palette/case-link/services/linked-cases.service.ts

https://tools.hmcts.net/jira/browse/EUI-5681
Link cases- Duplicate case Links- unhappy path
```
[ ] Yes
[ x ] No
```

story/EUI-5681 Case link check

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.html
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.spec.ts
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.ts
src/shared/components/palette/case-link/components/write-linked-cases.component.ts

https://tools.hmcts.net/jira/browse/EUI-5617
Unlink case: Manage case link event
```
[ ] Yes
[X] No
```

EUI-5617 Manage case link event

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.html
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.spec.ts
src/shared/components/palette/case-flag/enums/index.ts
src/shared/components/palette/case-flag/enums/manage-case-flag-type.enum.ts
src/shared/components/palette/case-flag/enums/select-flag-error-message.enum.ts

[EUI-5190](https://tools.hmcts.net/jira/browse/EUI-5190)
Add page validation to display an error if the user makes no selection or does not click "Next".
```
[ ] Yes
[x] No
```

EUI-5190: Manage Case Flags - "Select case flag" page validation

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.html
src/shared/components/palette/case-link/components/check-your-answers/check-your-answers.component.html
src/shared/components/palette/case-link/components/link-cases/link-cases.component.html
src/shared/components/palette/case-link/components/link-cases/link-cases.component.spec.ts
src/shared/components/palette/case-link/components/link-cases/link-cases.component.ts
src/shared/components/palette/case-link/components/unlink-cases/unlink-cases.component.html
src/shared/components/palette/case-link/components/unlink-cases/unlink-cases.component.ts
src/shared/components/palette/case-link/components/write-linked-cases.component.spec.ts
src/shared/components/palette/case-link/components/write-linked-cases.component.ts
src/shared/components/palette/case-link/domain/linked-cases-state.model.ts
src/shared/components/palette/case-link/enums/write-linked-cases-field.enum.ts

https://tools.hmcts.net/jira/browse/EUI-5732
Unlink case: Unlink case page-Exceptions 
```
[ ] Yes
[X] No
```

EUI-5732 Unlink case page exceptions

---

RELEASE-NOTES.md
package.json
src/shared/components/case-list/case-list.component.html
src/shared/components/case-list/case-list.component.spec.ts
src/shared/components/case-list/case-list.component.ts
src/shared/components/case-list/case-list.module.ts

EUI-5736
```
[ ] Yes
[ ] No
```

EUI-5736-pagination

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.ts
src/shared/components/palette/case-flag/enums/add-comments-step.enum.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.html
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-5973
Create case flag - Review flag details page - Pending Work (Part 3)
```
[ ] Yes
[X] No
```

EUI-5973 Case flag comments

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts

https://tools.hmcts.net/jira/browse/EUI-5743
mandatory-validation-in-collection
```
[ ] Yes
[x] No
```

EUI-5743-mandatory-validation-in-collection

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-5848
Manage case flags - Change to Update flag screen to indicate if Comments are mandatory or optional  
```
[ ] Yes
[X] No
```

EUI-5848 Flag comments mandatory or optional

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-from-table.component.html
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.html
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.spec.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.ts

https://tools.hmcts.net/jira/browse/EUI-5931
Find and display Case_name
```
[ ] Yes
[ x] No
```

EUI-5931 - display internal case name as missing

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.html
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.ts
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.html
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.ts
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.html
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.spec.ts
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.html
src/shared/components/palette/case-flag/read-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts
src/shared/services/fields/fields.utils.spec.ts
src/shared/services/fields/fields.utils.ts
src/shared/services/form/form-value.service.ts

[EUI-6043](https://tools.hmcts.net/jira/browse/EUI-6043)
Ensure that any previous case flag being created is removed if the user restarts the "Create Case Flag" journey.
```
[ ] Yes
[x] No
```

EUI-6043: Review Flag Details page - fix for "Change" link functionality

---

package.json
src/shared/components/case-editor/services/convert-href-to-router.service.spec.ts
src/shared/components/case-editor/services/convert-href-to-router.service.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.html
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
src/shared/components/markdown/markdown.component.spec.ts
src/shared/components/markdown/markdown.component.ts

https://tools.hmcts.net/jira/browse/EUI-6075
Added hash navigation
```
[ ] Yes
[ ] No
```

EUI:6075 - Added hash navigation

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
src/shared/components/case-editor/case-edit-submit/case-edit-submit.html
src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.ts
src/shared/components/palette/case-flag/case-flag.module.ts
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.html
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts
src/shared/components/palette/case-flag/components/add-comments/add-comments.component.ts
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.html
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.spec.ts
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.ts
src/shared/components/palette/case-flag/components/index.ts
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.html
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.spec.ts
src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.html
src/shared/components/palette/case-flag/read-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts
src/shared/services/fields/fields.utils.spec.ts
src/shared/services/fields/fields.utils.ts
src/shared/services/form/form-value.service.ts

[EUI-5968](https://tools.hmcts.net/jira/browse/EUI-5968)
Render an alternate version of the `ReadCaseFlagField` component, showing the new flag details in a summary list, for the "Check your answers" page.
```
[ ] Yes
[x] No
```

EUI-5968: Review Flag Details page - amend layout and content

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.html
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.spec.ts
src/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.ts
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
src/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
src/shared/components/palette/case-flag/domain/case-flag-state.model.ts
src/shared/components/palette/case-flag/enums/case-flag-summary-list-display-mode.enum.ts
src/shared/components/palette/case-flag/enums/index.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.html
src/shared/components/palette/case-flag/read-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.html
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts

[EUI-6168](https://tools.hmcts.net/jira/browse/EUI-6168)
Fix "Review flag details" page to work when updating a flag (Manage Case Flags journey).
```
[ ] Yes
[x] No
```

EUI-6168: Manage Case Flags - Review Flag Details page

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-flag/read-case-flag-field.component.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/write-case-flag-field.component.ts

[EUI-6148](https://tools.hmcts.net/jira/browse/EUI-6148)
[EUI-6155](https://tools.hmcts.net/jira/browse/EUI-6155)
[EUI-6156](https://tools.hmcts.net/jira/browse/EUI-6156)
Various bug fixes: EUI-6148 - discarded Case Flag details being persisted when restarting the Create Case Flag or Manage Case Flags journeys; EUI-6155 - change to case flag status is not being reflected; EUI-6156 - last modified date is not being updated when a case flag is updated.
```
[ ] Yes
[x] No
```

EUI-6148/EUI-6155/EUI-6156: Case Flag details persistence fixes

---

src/shared/components/event-start/event-guard/event-start.guard.ts

https://tools.hmcts.net/jira/browse/EUI-6246
```
[ ] Yes
[ x ] No
```

checkTaskInEventNotRequired

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.html
src/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.scss

[EUI-6198](https://tools.hmcts.net/jira/browse/EUI-6198)
Increase table caption font size and width of first column.
```
[ ] Yes
[x] No
```

EUI-6198: Case Flags table styling changes

---

package.json
src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.ts
src/shared/services/alert/alert.service.ts

https://tools.hmcts.net/jira/browse/EUI-6286
alert message banner disappearing
```
[ ] Yes
[x] No
```

preserve alerts after event completion

---

RELEASE-NOTES.md
package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
src/shared/components/palette/case-link/case-link.module.ts
src/shared/components/palette/case-link/components/check-your-answers/check-your-answers.component.spec.ts
src/shared/components/palette/case-link/components/check-your-answers/check-your-answers.component.ts
src/shared/components/palette/case-link/components/link-cases/link-cases.component.spec.ts
src/shared/components/palette/case-link/components/link-cases/link-cases.component.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-from-table.component.html
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-from-table.component.spec.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-from-table.component.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.html
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.spec.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.ts
src/shared/components/palette/case-link/components/read-linked-cases.component.ts
src/shared/components/palette/case-link/domain/linked-cases.model.ts
src/shared/components/palette/case-link/services/jurisdiction.service.ts
src/shared/components/palette/case-link/services/linked-cases.service.ts
src/shared/pipes/link-cases-reason-code/ccd-link-cases-reason-code.pipe.spec.ts
src/shared/services/jurisdiction/jurisdiction.service.ts

https://tools.hmcts.net/jira/browse/EUI-6462
Linked Cases - To Table - Map lookup ID into display value
```
[ ] Yes
[x] No
```

Feature/e UI 6462

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
src/shared/components/case-editor/services/page-validation.service.ts
src/shared/components/palette/base-field/abstract-form-field.component.ts
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.spec.ts
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.ts
src/shared/components/palette/case-link/components/link-cases/link-cases.component.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.html
src/shared/components/palette/case-link/components/read-linked-cases.component.ts
src/shared/components/palette/case-link/components/write-linked-cases.component.html
src/shared/components/palette/case-link/components/write-linked-cases.component.ts
src/shared/components/palette/case-link/write-case-link-field.component.ts
src/shared/components/palette/case-link/write-case-link-field.html
src/shared/components/palette/complex/ccd-read-fields-filter.pipe.ts

https://tools.hmcts.net/jira/browse/EUI-5892
https://tools.hmcts.net/jira/browse/EUI-5893
https://tools.hmcts.net/jira/browse/EUI-6502
Display error message when Continue is clicked instead of Next in Link cases journey
```
[ ] Yes
[ x] No
```

Feature/e UI 6502

---

RELEASE-NOTES.md
package.json
src/shared/components/case-editor/services/page-validation.service.ts
src/shared/components/palette/case-link/components/link-cases/link-cases.component.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.spec.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.ts
src/shared/components/palette/case-link/components/write-linked-cases.component.ts

https://tools.hmcts.net/jira/browse/EUI-6505
Ordering list items
```
[ ] Yes
[x ] No
```

linked cases to ordering the item lead/prog case on top

---

RELEASE-NOTES.md
package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.html

[EUI-6551](https://tools.hmcts.net/jira/browse/EUI-6551)
Revert erroneous HTML tag change, which causes an alignment anomaly.
```
[ ] Yes
[x] No
```

EUI-6551: Fix incorrect alignment of tabular display on tabs

---

src/shared/components/activity/activity.component.html
src/shared/components/activity/activity.module.ts
src/shared/components/palette/base-field/base-field.module.ts
src/shared/components/palette/base-field/field-read-label.html
src/shared/components/palette/palette.module.ts
src/shared/components/search-result/search-result.component.html
src/shared/components/search-result/search-result.module.ts
src/shared/components/workbasket-filters/workbasket-filters.component.html
src/shared/components/workbasket-filters/workbasket-filters.module.ts

https://tools.hmcts.net/jira/browse/EUI-6534
Added rpxTranslate pipe to all the strings
```
[ ] Yes
[x] No
```

Feature/e UI 6534

---

package.json
src/shared/domain/case-view/role-request.model.ts

https://tools.hmcts.net/jira/browse/EUI-6180
Add new role - CTSC
```
[ ] Yes
[ x] No
```

Add CTSC role

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-link/components/link-cases/link-cases.component.spec.ts
src/shared/components/palette/case-link/components/link-cases/link-cases.component.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.ts
src/shared/components/palette/case-link/components/read-linked-cases.component.html
src/shared/components/palette/case-link/components/write-linked-cases.component.ts
src/shared/components/palette/case-link/services/linked-cases.service.ts

https://tools.hmcts.net/jira/browse/EUI-6598
```
[ ] Yes
[ x] No
```

Link unlink cases validation fix

---

package.json
src/shared/components/event-start/event-guard/event-start.guard.spec.ts
src/shared/components/event-start/event-guard/event-start.guard.ts

https://tools.hmcts.net/jira/browse/EUI-6473
Remove MVP code
```
[ ] Yes
[ x] No
```

EUI 6473 removing mvp

---

package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
src/shared/components/palette/complex/read-complex-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-6328
positioning tab
```
[ ] Yes
[x] No
```

EUI-6328-tab-positioning

---

package.json
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.html
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.spec.ts
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.ts
src/shared/components/palette/case-link/components/no-linked-cases/no-linked-cases.component.html
src/shared/components/palette/case-link/components/read-linked-cases.component.ts
src/shared/components/palette/case-link/components/write-linked-cases.component.ts
src/shared/components/palette/case-link/services/linked-cases.service.ts

https://tools.hmcts.net/jira/browse/EUI-6714
https://tools.hmcts.net/jira/browse/EUI-6714
```
[ ] Yes
[ x] No
```

Feature/e UI 6714

---

package.json
src/shared/components/palette/case-link/components/before-you-start/before-you-start.component.html

https://tools.hmcts.net/jira/browse/EUI-6714
https://tools.hmcts.net/jira/browse/EUI-6714
```
[ ] Yes
[x] No
```

manage case links api error handling

---

src/shared/components/palette/base-field/field-write.component.spec.ts
src/shared/components/palette/base-field/field-write.component.ts

https://tools.hmcts.net/jira/browse/EUI-6513
Need to revert the changes done in 6513.
```
[ ] Yes
[X] No
```

reverting the changes done in 6513

---

package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts

https://tools.hmcts.net/jira/browse/EUI-6328
Tab navigation issue
```
[ ] Yes
[x] No
```

EUI 6328 tab redirection issue rc1

---

package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts

https://tools.hmcts.net/jira/browse/EUI-6328
tab redirection issue
```
[ ] Yes
[x] No
```

EUI 6328 revert

---

package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
src/shared/components/case-viewer/services/case.resolver.spec.ts
src/shared/components/case-viewer/services/case.resolver.ts

https://tools.hmcts.net/jira/browse/EUI-6741
Redirect to no cases found 
```
[ ] Yes
[x] No
```

EUI - 6741 - Fix the issue with tab selection

---

package.json
src/shared/components/case-editor/case-access-utils/index.ts
src/shared/components/case-editor/services/cases.service.ts

https://tools.hmcts.net/jira/browse/EUI-6839
Added update methods
added accessReason in attributes
```
[ ] Yes
[x] No
```

Feature/e UI 6839

---

package.json
src/shared/components/case-viewer/case-viewer.component.spec.ts
src/shared/components/case-viewer/case-viewer.component.ts

https://tools.hmcts.net/jira/browse/EUI-6891
Check Acess grant and full view
```
[ ] Yes
[x] No
```

EUI-6891 Add check for acess grant

---

package.json
src/shared/components/case-viewer/case-challenged-access-success/case-challenged-access-success.component.spec.ts
src/shared/components/case-viewer/case-challenged-access-success/case-challenged-access-success.component.ts
src/shared/components/case-viewer/case-specific-access-success/case-specific-access-success.component.spec.ts
src/shared/components/case-viewer/case-specific-access-success/case-specific-access-success.component.ts

https://tools.hmcts.net/jira/browse/EUI-6921
Fix to display the correct case referecne from the route
```
[ ] Yes
[x] No
```

EUI-6921 Fix old case ref issues

---

RELEASE-NOTES.md
demo/src/app/app.config.ts
package.json
src/app-config.mock.ts
src/app.config.ts
src/shared/components/palette/waystopay/waystopay-field.component.spec.ts
src/shared/domain/case-file-view/case-file-view-category.model.ts
src/shared/domain/case-file-view/case-file-view-document.model.ts
src/shared/domain/case-file-view/categories-and-documents.model.ts
src/shared/domain/case-file-view/index.ts
src/shared/services/case-file-view/case-file-view.service.spec.ts
src/shared/services/case-file-view/case-file-view.service.ts
src/shared/services/case-file-view/index.ts
src/shared/services/index.ts

[EUI-5481](https://tools.hmcts.net/jira/browse/EUI-5481)
Service layer for HTTP GET call to CCD Data Store API endpoint for retrieving categories and documents.
```
[ ] Yes
[x] No
```

EUI-5481: Case File View - CCD API endpoint for Categories and Documents

---

RELEASE-NOTES.md
demo/src/app/app.config.ts
package.json
src/app-config.mock.ts
src/app.config.ts
src/shared/components/palette/waystopay/waystopay-field.component.spec.ts
src/shared/services/case-file-view/case-file-view.service.spec.ts
src/shared/services/case-file-view/case-file-view.service.ts

[EUI-6815](https://tools.hmcts.net/jira/browse/EUI-6815)
Service layer for HTTP PUT call to CCD Data Store API endpoint for updating category for a document.
```
[ ] Yes
[x] No
```

EUI-6815: Case File View - CCD API endpoint for Document Data

---

package.json
src/shared/components/case-editor/services/case.notifier.spec.ts
src/shared/components/case-editor/services/case.notifier.ts
src/shared/components/case-editor/services/cases.service.ts
src/shared/components/case-viewer/case-basic-access-view/case-basic-access-view.component.html
src/shared/components/case-viewer/case-basic-access-view/case-basic-access-view.component.spec.ts
src/shared/components/case-viewer/case-basic-access-view/case-basic-access-view.component.ts

https://tools.hmcts.net/jira/browse/EUI-7006
Set basic fields
```
[ ] Yes
[x] No
```

Set basic fields

---

RELEASE-NOTES.md
package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.html
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
src/shared/components/palette/case-file-view/case-file-view-field.component.html
src/shared/components/palette/case-file-view/case-file-view-field.component.ts
src/shared/components/palette/complex/ccd-read-fields-filter.pipe.ts
src/shared/components/palette/palette.service.spec.ts
src/shared/components/palette/palette.service.ts
src/shared/domain/definition/field-type-enum.model.ts

[EUI-6965](https://tools.hmcts.net/jira/browse/EUI-6965)
Implement the `ComponentLauncher` mechanism for invoking the Case File View web component.
```
[ ] Yes
[x] No
```

EUI-6965: Case File View - ComponentLauncher mechanism

---

package.json
src/shared/components/search-result/search-result.component.html

[EUI-7040](https://tools.hmcts.net/jira/browse/EUI-7040)
```
[ ] Yes
[x] No
```

EUI-7040 Fixed Reset case selection link due to console errors

---

package.json
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
src/shared/components/case-editor/case-edit/case-edit.component.spec.ts
src/shared/components/case-editor/case-edit/case-edit.component.ts
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
src/shared/components/search-result/search-result.component.spec.ts
src/shared/components/search-result/search-result.component.ts
src/shared/directives/substitutor/label-substitutor.directive.ts
src/shared/services/window/window.service.spec.ts
src/shared/services/window/window.service.ts

https://tools.hmcts.net/jira/browse/EUI-7004
FR cases submitted without mandatory fields
```
[ ] Yes
[x] No
```

EUI-7004-refresh page clear the filled data

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-confirm/case-edit-confirm.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.html
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/cdd-page-fields.pipe.ts

[EUI-7147](https://tools.hmcts.net/jira/browse/EUI-7147)
```
[x] Yes
[ ] No
```

Bug/e UI 7147 cya fix

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-from-table.component.html
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.html
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.spec.ts
src/shared/components/palette/case-link/components/linked-cases-table/linked-cases-to-table.component.ts
src/shared/components/palette/case-link/components/no-linked-cases/no-linked-cases.component.html
src/shared/components/palette/case-link/components/no-linked-cases/no-linked-cases.component.ts
src/shared/components/palette/case-link/components/write-linked-cases.component.ts
src/shared/components/palette/case-link/services/linked-cases.service.ts

https://tools.hmcts.net/jira/browse/EUI-7234
https://tools.hmcts.net/jira/browse/EUI-7245
https://tools.hmcts.net/jira/browse/EUI-7250
Case link unlink integration bugs
```
[ ] Yes
[X] No
```

Case link unlink integration bugs

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-link/components/unlink-cases/unlink-cases.component.spec.ts
src/shared/components/palette/case-link/components/unlink-cases/unlink-cases.component.ts

https://tools.hmcts.net/jira/browse/EUI-7219
Case name missing in UI even after adding from Service
```
[ ] Yes
[X] No
```

EUI-7219 Case name missing unlink journey

---

RELEASE-NOTES.md
package.json
src/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts

https://tools.hmcts.net/jira/browse/EUI-7327
PRL - Keeps jumping between Case flag and case hearing tab whenever user is directed to hearings tab
```
[ ] Yes
[X] No
```

EUI-7327 Flickering issue

---

package.json
src/shared/components/palette/case-link/components/link-cases/link-cases.component.ts

https://tools.hmcts.net/jira/browse/EUI-7257
Prevent case linking to 'Already Linked' to & 'Linked from' cases
```
[ ] Yes
[ x ] No
```

7.0.9-prevent-case-linking fix

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/case-file-view-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.ts

[EUI-6866](https://tools.hmcts.net/jira/browse/EUI-6866)
Implement print and download functions for the document context menu.
```
[ ] Yes
[x] No
```

EUI-6866: Case File View - print and download functions

---

RELEASE-NOTES.md
package.json
src/shared/services/form/form-value.service.spec.ts
src/shared/services/form/form-value.service.ts

[EUI-7377](https://tools.hmcts.net/jira/browse/EUI-7377)
Fix to ensure case event data object gets populated correctly with data from all case fields whose ID exists in the data object.
```
[ ] Yes
[x] No
```

EUI-7377: Case Flags defect fix

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/palette.service.ts

https://tools.hmcts.net/jira/browse/EUI-7413
Case links enable backward compatibility
```
[ ] Yes
[X] No
```

EUI-7413 Case links enable backward compatibility

---

RELEASE-NOTES.md
package.json
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.html
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.scss
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts
src/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
src/shared/components/palette/case-flag/domain/case-flag.model.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.html
src/shared/components/palette/case-flag/read-case-flag-field.component.spec.ts
src/shared/components/palette/case-flag/read-case-flag-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-7353
https://tools.hmcts.net/jira/browse/EUI-7355
Case flags title and style changes
```
[ ] Yes
[X] No
```

EUI-7353 Case flags title and style changes

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-challenged-access-success/case-challenged-access-success.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/history/event-log/event-log-table.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/utils/is-compound.pipe.ts

https://tools.hmcts.net/jira/browse/EUI-7454
Tables are not correctly aligned
```
[ ] Yes
[X] No
```

EUI-7454 Tables are not correctly aligned

---

projects/ccd-case-ui-toolkit/src/lib/shared/commons/case-edit-data/case-edit-data.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/commons/case-edit-data/case-edit-data.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/commons/case-edit-data/case-edit-validation.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/commons/case-edit-data/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-editor.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-link/components/write-linked-cases.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-link/write-case-link-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-link/write-case-link-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/index.ts

https://tools.hmcts.net/jira/browse/EUI-7457
Added a data sharing module to exchange data between the case editor module and others
```
[ ] Yes
[x] No
```

Feature/e UI 7457 case link

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-link/components/link-cases/link-cases.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-link/components/write-linked-cases.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-link/components/write-linked-cases.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/utils/is-compound.pipe.ts

https://tools.hmcts.net/jira/browse/EUI-7457
Linked cases not proceeding after the first page
```
[ ] Yes
[X] No
```

EUI-7457 Linked cases not proceeding after the first page

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/commons/case-edit-data/case-edit-data.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/read-case-flag-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.ts

https://tools.hmcts.net/jira/browse/EUI-7453
Continue button is not working on comments in Case Flags
```
[ ] Yes
[X] No
```

EUI-7453 Case flags integration issues

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag-welsh-translation-form/update-flag-welsh-translation-form.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag-welsh-translation-form/update-flag-welsh-translation-form.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag-welsh-translation-form/update-flag-welsh-translation-form.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/case-flag-status.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-states.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-step.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/write-case-flag-field.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/generic/enum-display-description/enum-display-description.pipe.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/generic/enum-display-description/enum-display-description.pipe.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/generic/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/pipes.module.ts

https://tools.hmcts.net/jira/browse/EUI-7349
View and edit ‘Add Welsh translations to flag’
```
[ ] Yes
[x] No
```

Feature/e UI 7349

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.scss

https://tools.hmcts.net/jira/browse/EUI-7665
alignment issue

Feature/e UI 7665 alignment issue

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-history/case-history.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/directives/conditional-show/domain/conditional-show.model.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/directives/conditional-show/domain/conditional-show.model.ts

https://tools.hmcts.net/jira/browse/EUI-7745
Summary screen is not showing all fields
```
[ ] Yes
[ x ] No
```

bug/EUI-7745 

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/check-your-answers/check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/check-your-answers/check-your-answers.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/check-your-answers/check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/link-cases/link-cases.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/link-cases/link-cases.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/linked-cases-table/linked-cases-from-table.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/linked-cases-table/linked-cases-from-table.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/linked-cases-table/linked-cases-to-table.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/linked-cases-table/linked-cases-to-table.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/linked-cases-table/linked-cases-to-table.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/domain/linked-cases.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/enums/write-linked-cases-field.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/services/linked-cases.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/link-cases-from-reason-code/ccd-link-cases-from-reason-code.pipe.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/link-cases-from-reason-code/ccd-link-cases-from-reason-code.pipe.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/link-cases-from-reason-code/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/link-cases-reason-code/ccd-link-cases-reason-code.pipe.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/link-cases-reason-code/ccd-link-cases-reason-code.pipe.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/pipes.module.ts

https://tools.hmcts.net/jira/browse/EUI-7246
No textbox available when the checkbox for Other is selected on Link Reasons page
```
[ ] Yes
[X] No
```

EUI-7246 Linked cases capture other reason

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/confirm-flag-status/confirm-flag-status.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/confirm-flag-status/confirm-flag-status.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/confirm-flag-status/confirm-flag-status.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/confirm-status-error-message.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/index.ts

[EUI-7611](https://tools.hmcts.net/jira/browse/EUI-7611)
Add validation to display an error if the user exceeds the 200-character limit for the status reason, or if they do not provide a status reason when "Not approved" is selected.
```
[ ] Yes
[x] No
```

EUI-7611: Case Flags v2 - Confirm flag status step validation

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/case-flag-wizard-step-title.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/select-flag-error-message.enum.ts

https://tools.hmcts.net/jira/browse/EUI-7371
Manage support first step text changes
```
[ ] Yes
[X] No
```

Feature/e UI 7371

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.ts

EUI-7929
Set the valid flag status options available on the "Update flag" page, based on the current status of the selected flag.
```
[ ] Yes
[x] No
```

EUI-7929: Case Flags v2 - Set valid status progressions for flag updates

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/app-config.mock.ts
projects/ccd-case-ui-toolkit/src/lib/app.config.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/base-field/payment-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/payment/case-payment-history-viewer-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/payment/case-payment-history-viewer-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/waystopay/waystopay-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/waystopay/waystopay-field.component.spec.ts
yarn.lock

Reverts hmcts/ccd-case-ui-toolkit#1343

Revert "Refunds V2 web component integration"

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/confirm-flag-status/confirm-flag-status.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/confirm-flag-status/confirm-flag-status.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag-add-translation-form/update-flag-add-translation-form.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag-add-translation-form/update-flag-add-translation-form.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts

https://tools.hmcts.net/jira/browse/EUI-7992
Reasonable Adjustments - Legal Rep - Ensure all content visible to professional users can be translated to Welsh
```
[ ] Yes
[ x ] No
```

EUI-7992 case-flags-welsh-language-reasonable-adj

---

.github/workflows/npmpublish.yml
package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

Publish fix. Using npm to control the publish instead of yarn.
```
[ ] Yes
[x] No
```

Publish fix

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/app-config.mock.ts
projects/ccd-case-ui-toolkit/src/lib/app.config.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/base-field/payment-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/payment/case-payment-history-viewer-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/payment/case-payment-history-viewer-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/waystopay/waystopay-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/waystopay/waystopay-field.component.spec.ts
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-7489
refund v2
```
[ ] Yes
[ ] No
```

EUI 7489 refund v2

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/app-config.mock.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/components/linked-cases-table/linked-cases-to-table.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/__mocks__/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-create/query-create.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-create/query-create.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-detail/query-detail.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-detail/query-detail.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/query-management.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/utils/query-management.utils.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/utils/query-management.utils.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/write-query-management-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/write-query-management-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/definition/display-context-enum.model.ts

https://tools.hmcts.net/jira/browse/EUI-8303
Orchestrator to get the 'Query management' mock data (interim)
```
[ ] Yes
[X] No
```

EUI-8303 Query Management orchestrator to get the mock data

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.html
projects/ccd-case-ui-toolkit/src/lib/shared/domain/profile/profile.test.fixture.ts

https://tools.hmcts.net/jira/browse/EUI-8286
Reasonable Adjustment - Legal Rep Request support - Amend the CYA page to remove Event Summary and Event Description sections
```
[ ] Yes
[X] No
```

EUI-8286 Reasonable Adjustments CYA hide event summary section

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/pipes/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/pipes/update-flag-title-display.pipe.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/pipes/update-flag-title-display.pipe.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
yarn.lock

EUI-8370
EUI-8371
EUI-8370: Ensure "Other" support type is not shown at the top-level selection when the user is external; EUI-8371: Show details of the selected support being updated when the user is external.
```
[ ] Yes
[x] No
```

EUI-8370/EUI-8371: Case Flags v2 - Reasonable Adjustments fixes

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/__mocks__/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-detail/query-detail.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.scss
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/party-messages/party-message.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/party-messages/party-messages-group.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/query-list/query-list-data/query-list-data.model.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/query-list/query-list-data/query-list-data.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/query-list/query-list-item/query-list-item.model.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/query-list/query-list-item/query-list-item.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/domain/query-list/query-list-response-status.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.ts
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-8112
Query list display ticket
```
[ ] Yes
[X] No
```

Feature/e UI 8112

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/definition/display-context-enum.model.ts

N/A
Added handling for the QueryManagementWriteTest context param
```
[ ] Yes
[X] No
```

QM WriteTest paletteService changes

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts

https://tools.hmcts.net/jira/browse/EXUI-110
Infinite tab loop fix
```
[ ] Yes
[x] No
```

EXUI-110 Infinite tab loop fix

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/case-view/case-view-event-ids.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/case-view/case-view-trigger.model.ts
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-8396
Added handling for the the 'raise query' event
```
[ ] Yes
[X] No
```

Feature/e UI 8396

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html

https://tools.hmcts.net/jira/browse/EUI-8428
text change
```
[ ] Yes
[X] No
```

Feature/e UI 8428

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-raise-query/query-write-raise-query.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.ts

https://tools.hmcts.net/jira/browse/EUI-8483
Add full name input
```
[ ] Yes
[X] No
```

Feature/e UI 8483

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/__mocks__/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/models/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/models/qualifying-questions/casetype-qualifying-questions.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/models/qualifying-questions/qualifying-question.model.ts

https://tools.hmcts.net/jira/browse/EUI-8522
Create DataModel and mockdata
```
[ ] Yes
[X] No
```

EUI-8522 QQ create data model and mock data

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/models/query-list/query-list-item/query-list-item.model.spec.ts

https://tools.hmcts.net/jira/browse/EUI-8603
Query Management - New CYA for Raise a query 
```
[ ] Yes
[X] No
```

EUI-8603 QM raise a query cya

---

package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

[EXUI-360](https://tools.hmcts.net/jira/browse/EXUI-360)

EXUI-360: ccpay upgrade to 5.2.8-beta04

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details-table/query-details-table.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.scss
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.scss

https://tools.hmcts.net/jira/browse/EUI-8623
Query Management - Remove grey bar from Tab and Details page
```
[ ] Yes
[X] No
```

EUI-8623 QM remove grey bar

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details-table/query-details-table.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details-table/query-details-table.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.spec.ts

https://tools.hmcts.net/jira/browse/EUI-8609
UI changes in respond query
```
[ ] Yes
[x] No
```

UI changes

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
yarn.lock

EUI-8630
Fix and re-enable unit tests for the `CaseEditPageComponent`, which account for a significant proportion of the missing coverage. Also implement clean-up of several subscriptions to `Observable`s.
```
[ ] Yes
[x] No
```

EUI-8630: Increase CCD Toolkit unit test coverage

---

package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
yarn.lock

None.
Merge `master` branch into `Release`.
```
[ ] Yes
[x] No
```

Update Release branch with master

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts

https://tools.hmcts.net/jira/browse/EXUI-343
Text not showing in the "Continue" green button
```
[ ] Yes
[x] No
```

Ex UI 343 button text missing

---

.nyc_output/.gitkeep
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/case.notifier.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/cases.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-view/case-view.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-viewer.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/services/case.resolver.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/http/http-error.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/loading/loading.service.ts
projects/ccd-case-ui-toolkit/tslint.json

https://tools.hmcts.net/jira/browse/EXUI-681
add console logs.
```
[ ] Yes
[X] No
```

add console logs

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/add-comments-step.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-step.enum.ts

https://tools.hmcts.net/jira/browse/EUI-8709
https://tools.hmcts.net/jira/browse/EUI-8710
EUI-8709 - Case flags v2.1 add warning text to create case flag journey
EUI-8710 - Case flags v2.1 add warning text to update case flag journey
```
[ ] Yes
[X] No
```

EUI-8709 EUI-8710 Case flags v2.1 add warning message

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json

This PR is to update case flags v2 version and merge it into Release.
```
[ ] Yes
[X] No
```

Update case flags v2 for release

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/services/utils/retry/retry.service.ts

https://tools.hmcts.net/jira/browse/EXUI-700
fix non-timeout error handling
```
[ ] Yes
[X] No
```

fix non-timeout error handling

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-editor.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-event-completion/case-event-completion.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-event-completion/components/case-event-completion-task-cancelled/case-event-completion-task-cancelled.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-event-completion/components/case-event-completion-task-reassigned/case-event-completion-task-reassigned.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-event-completion/query-event-completion.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-event-completion/query-event-completion.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-event-completion/query-event-completion.component.ts

https://tools.hmcts.net/jira/browse/EUI-8600
Respond Query - Complete task using event completion workflow 
```
[ ] Yes
[x] No
```

Move modules

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-submit/case-edit-submit.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/add-comments-error-message.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/add-comments-step.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/case-flag-check-your-answers-step.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/case-flag-wizard-step-title.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/select-flag-type-error-message.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-error-message.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-step.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/fields/fields.utils.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/fields/fields.utils.ts

https://tools.hmcts.net/jira/browse/EUI-8779
Reasonable adjustments - update base branch with un-merged code
```
[ ] Yes
[X] No
```

EUI-8779 Reasonable adjustments - update base branch with un-merged code

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.spec.ts

EXUI-623
Fix exception in unit tests caused by not mocking a method called by the code
```
[ ] Yes
[ x] No
```

Fixing exception in unit tests

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-error-message.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-step.enum.ts

EUI-8840
Use flagUpdateComment field for persisting flag comments on update by external users.
```
[ ] Yes
[x] No
```

EUI-8840: Case Flags v2 - Update flag for external users fix

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-editor.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/valid-page-list-caseFields.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/valid-page-list-caseFields.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.spec.ts

EXUI_837
Different approach to page visibility on submit
```
[ ] Yes
[ ] No
```

Exui 837 cya fix

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts

EUI-8947
EXUI-848
Fix bug introduced by change to `CaseEditComponent` case event data generation in EXUI-848.
```
[ ] Yes
[x] No
```

EUI-8947: Case Flags - Fix bug caused by EXUI-848

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/ccd-read-fields-filter.pipe.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/ccd-read-fields-filter.pipe.ts

https://tools.hmcts.net/jira/browse/EXUI-998
https://tools.hmcts.net/jira/browse/EXUI-1000
https://tools.hmcts.net/jira/browse/EXUI-1006
Complex type not showing data
Case Flags stopped working
```
[ ] Yes
[x] No
```

exui-1006-avoid hidden field deletion fr case flag

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/complex/read-complex-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/complex/read-complex-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/fields/fields.utils.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/fields/fields.utils.ts

EUI-8918
EUI-8968
EUI-8918: Fix `CaseEventTriggerComponent` to bypass case validation only if a `FlagLauncher` case field is present in the eventTrigger case fields, instead of being present in any `CaseTab` case fields.
EUI-8968: Fix missing validation error message on clicking "Continue" button when Case Flags v2.1 is enabled.
```
[ ] Yes
[x] No
```

EUI-8918: Case Flags fix and EUI-8968: Case Flags v2.1 fixes

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-event-completion/components/case-event-completion-task-reassigned/case-event-completion-task-reassigned.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-event-completion/components/case-event-completion-task-reassigned/case-event-completion-task-reassigned.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/event-completion-state-machine.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/datetime-picker/datetime-picker-component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/datetime-picker/datetime-picker-utils.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/case-view/service-org-response.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/ccd-read-fields-filter.pipe.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/ccd-read-fields-filter.pipe.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/common-data-service/common-data-service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/common-data-service/common-data-service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/fields/fields.purger.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/fields/fields.purger.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/form/form-value.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/form/form-value.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/utils/retry/retry.service.ts

https://tools.hmcts.net/jira/browse/EXUI-812
https://tools.hmcts.net/jira/browse/EXUI-1038
https://tools.hmcts.net/jira/browse/EXUI-1042
https://tools.hmcts.net/jira/browse/EXUI-1112
https://tools.hmcts.net/jira/browse/EXUI-1121
https://tools.hmcts.net/jira/browse/EXUI-1137
https://tools.hmcts.net/jira/browse/EXUI-1152
https://tools.hmcts.net/jira/browse/EXUI-830
https://tools.hmcts.net/jira/browse/EXUI-1229
MC Release 7.0.4
```
[ ] Yes
[ ] No
```

Mc release 7.0.4

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts

https://tools.hmcts.net/jira/browse/EXUI-1330
```
[ ] Yes
[ ] No
```

File upload casetype field fix

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/services/organisation/organisation.service.ts

https://tools.hmcts.net/jira/browse/EXUI-1295
Fixing the cache functionality of the get organisations call
```
[ ] Yes
[ x ] No
```

Tech/e UI 1295 org cache performance

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/commons/address-validation-constants.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/address/write-address-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/address/write-address-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/address/write-address-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/base-field/abstract-form-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/linked-cases/write-linked-cases-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/http/http-error.model.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/http/http-error.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/addresses/addresses.service.ts
sonar-project.properties

https://tools.hmcts.net/jira/browse/EXUI-1067
https://tools.hmcts.net/jira/browse/EXUI-1123
```
[ ] Yes
[x] No
```

Exui 1350 srt

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/yes-no/read-yes-no-field.component.ts

https://tools.hmcts.net/jira/browse/EXUI-1322
Welsh translation code has been incorrectly applied to the yes no field, resulting in the field label being displayed if the yesno is null
```
[ ] Yes
[ x] No
```

EXUI-1322 - more yes no problems

---

package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EXUI-1511
ccpay-upgrade
```
[ ] Yes
[x] No
```

exui-1511-ccpay-upgrade

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/test-data/categories-and-documents-test-data.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/test-data/document-tree-node-test-data.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/yes-no/read-yes-no-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/document/document-data.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/case-file-view/case-file-view.service.spec.ts

https://tools.hmcts.net/jira/browse/CSFD-95
if an upload_timestamp is present on a document for a case it will be passed through when update case event is called.
```
[ ] Yes
[x] No
```

add upload_timestamp to document-data.model

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/page-validation.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/page-validation.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/http/http-error.model.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/http/http-error.model.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/fields/fields.purger.ts

https://tools.hmcts.net/jira/browse/EXUI-724
https://tools.hmcts.net/jira/browse/EXUI-706
https://tools.hmcts.net/jira/browse/EXUI-830
https://tools.hmcts.net/jira/browse/EXUI-1184
https://tools.hmcts.net/jira/browse/EXUI-1194
https://tools.hmcts.net/jira/browse/EXUI-1304
https://tools.hmcts.net/jira/browse/EXUI-1453
https://tools.hmcts.net/jira/browse/EXUI-1455
```
[ ] Yes
[ ] No
```

Add error handling (#1681)

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder-selector/case-file-view-folder-selector.component.scss

https://tools.hmcts.net/jira/browse/EXUI-1449
```
[ ] Yes
[ ] No
```

caseview css changes

---

package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EXUI-1797
ccpay upgrade
```
[ ] Yes
[x ] No
```

exui-1797-ccpay upgrade

---

package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

updates web-component version

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/yes-no/read-yes-no-field.component.ts

fix missing label

---

package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EXUI-1870
ccpay upgrade
```
[ ] Yes
[x] No
```

exui-1870-ccpay upgrade

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/cases.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-viewer.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/services/case.resolver.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/services/event-start-state-machine.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/services/event-start-state-machine.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/markdown/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/markdown/markdown-component.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/markdown/markdown.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/markdown/markdown.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/markdown/markdown.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/markdown/routerlink.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/jurisdiction/jurisdiction.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/loading/loading.service.ts

https://tools.hmcts.net/jira/browse/EXUI-1793
remove isComplete route parameter. Doesn't seem to do anything useful.
Move code that removes the taskToComplete parameter to only do it when the taskToComplete code might then be reeded
```
[ ] Yes
[ x] No
```

Task Completion PRL issue EXUI-1793

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/history/event-log/event-log-table.component.html
yarn.lock

media viewer version update

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/services/event-trigger.resolver.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/services/event-trigger.resolver.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/error/callback-errors.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/error/callback-errors.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/error/domain/error-context.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-trigger/event-trigger.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-trigger/event-trigger.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-trigger/event-trigger.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/error/error-notifier.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/order/order.service.ts

https://tools.hmcts.net/jira/browse/EXUI-1974
```
[ ] Yes
[ ] No
```

callback event error bug fix

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/search-result/search-result.component.html

https://tools.hmcts.net/jira/browse/EXUI-1540
revert implementation of exui-1540
```
[ ] Yes
[x] No
```

revert exui-1540

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-trigger/event-trigger.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-trigger/event-trigger.component.ts

https://tools.hmcts.net/jira/browse/EXUI-2224
https://tools.hmcts.net/jira/browse/EXUI-2224
```
[ ] Yes
[x] No
```

exui-2224-enable go button

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EXUI-2209
MV Upgrade to v4.0.7
```
[ ] Yes
[x] No
```

EXUI-2209: MV Upgrade to v4.0.7

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts

https://tools.hmcts.net/jira/browse/EXUI-2235
add event name in app insight log while task completion
```
[ ] Yes
[x] No
```

exui-2235-add event name in app insight log while task completion

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/base-field/field-read.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/collection/read-collection-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/complex/read-complex-field-table.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/multi-select-list/multi-select-list.scss
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/multi-select-list/read-multi-select-list-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/multi-select-list/read-multi-select-list-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/search-result/search-result.component.html

Reverts hmcts/ccd-case-ui-toolkit#1693

Revert "Ex UI 1270 accessibility bug fixes"

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EXUI-2280
MV Upgrade to v4.0.8
```
[ ] Yes
[X] No
```

EXUI-2280: MV Upgrade to v4.0.8

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/app-config.mock.ts
projects/ccd-case-ui-toolkit/src/lib/app.config.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/waystopay/waystopay-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/window/window.service.spec.ts
src/app.config.ts

https://tools.hmcts.net/jira/browse/EXUI-2220
add logs
```
[ ] Yes
[x] No
```

exui-2220-add logs

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts

https://tools.hmcts.net/jira/browse/EXUI-2303
Avoid exception in log message if feature config isn't working 
```
[ ] Yes
[x] No
```

Fix exception in log message

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/resolvers/event-tasks-resolver.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/resolvers/event-tasks-resolver.service.ts

https://tools.hmcts.net/jira/browse/EXUI-2320
INC5645021-Intermittent missing call of search for completable
```
[ ] Yes
[x] No
```

exui-2320-add app insight logs

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/services/event-start-state-machine.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/domain/work-allocation/Task.ts

https://tools.hmcts.net/jira/browse/EXUI-2148
Add the necessary details to session storage (user ID, timestamp in addition in new object)

Add the necessary details to session storage

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-date-input/query-write-date-input.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.ts

https://tools.hmcts.net/jira/browse/EXUI-2095
```
[ ] Yes
[ ] No
```

Making respond to query button available for test

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts

Exui 2095 work around case collection issue

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/qualifying-questions/qualifying-question-options/qualifying-question-options.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/qualifying-questions/qualifying-question-options/qualifying-question-options.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/qualifying-questions/qualifying-question-options/qualifying-question-options.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.spec.ts

https://tools.hmcts.net/jira/browse/EXUI-2450
```
[ ] Yes
[ ] No
```

Exui 2450 caption link update

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/palette.module.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/qualifying-questions/qualifying-question-options/qualifying-question-options.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/qualifying-questions/qualifying-question-options/qualifying-question-options.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/services/index.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/services/qualifying-question.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/services/qualifying-question.service.ts

https://tools.hmcts.net/jira/browse/EXUI-2426
```
[ ] Yes
[ ] No
```

Exui 2426 back btn

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-attachments-read/query-attachments-read.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-attachments-read/query-attachments-read.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-attachments-read/query-attachments-read.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-add-documents/query-write-add-documents.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/utils/query-management.utils.ts

https://tools.hmcts.net/jira/browse/EXUI-2449
```
[ ] Yes
[ ] No
```

Exui 2449 document missing

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-list/query-list.component.scss

https://tools.hmcts.net/jira/browse/EXUI-2455
```
[ ] Yes
[ ] No
```

Exui 2455 multiparty queries

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/activity/activity.component.ts

https://tools.hmcts.net/jira/browse/EXUI-2354
```
[ ] Yes
[ ] No
```

exui-2354-search-issue

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json

up version number

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/case-header/case-header.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-case-details-header/query-case-details-header.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-case-details-header/query-case-details-header.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-case-details-header/query-case-details-header.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-raise-query/query-write-raise-query.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-raise-query/query-write-raise-query.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.ts

https://tools.hmcts.net/jira/browse/EXUI-2420
```
[ ] Yes
[ ] No
```

Exui 2420 name refernce missing

---

.github/workflows/npmpublish.yml
RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/complex/read-complex-field-table.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/complex/read-complex-field-table.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/complex/read-complex-field-table.html
projects/ccd-case-ui-toolkit/src/lib/shared/directives/conditional-show/services/condition-parser.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/pipes/complex/ccd-read-fields-filter.pipe.ts

https://tools.hmcts.net/jira/browse/EXUI-2346
Make fix to show unavailable dates (or any children within an array of a complex field's children
```
[ ] Yes
[ x ] No
```

Bug/ex UI 2346 hidden unavailable dates

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json

up ver num

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/utils/query-management.utils.ts

https://tools.hmcts.net/jira/browse/EXUI-2530
```
[ ] Yes
[ ] No
```

fix isHearingRelated Field Value Mismatch

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/date/read-date-field.component.ts

Reverts hmcts/ccd-case-ui-toolkit#1781

Revert "exui-2144-convert utc to local time"

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/dynamic-radio-list/write-dynamic-radio-list-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/dynamic-radio-list/write-dynamic-radio-list-field.component.ts

https://tools.hmcts.net/jira/browse/EXUI-2462
DynamicRadioList incorrectly selects the wrong radio button
```
[ ] Yes
[x ] No
```

Add the fix and tests

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/enums/query-item-response-status.enum.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/models/query-list/query-list-item/query-list-item.model.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/models/query-list/query-list-item/query-list-item.model.ts

https://tools.hmcts.net/jira/browse/EXUI-2525
```
[ ] Yes
[ ] No
```

update response status

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/qualifying-questions/qualifying-question-options/qualifying-question-options.component.html

Remove copy and link

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/event-start/event-guard/event-start.guard.ts

Fix regression issue that overwrites user_task
https://tools.hmcts.net/jira/browse/EXUI-2624
May also help to resolve https://tools.hmcts.net/jira/browse/EXUI-2621 as well as other similar issues
Fix regression issue where user_task overwritten
```
[ ] Yes
[ x ] No
```

Bug/ex UI 2624 user task missing

---

package.json
projects/ccd-case-ui-toolkit/package.json

version update

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json

incremement version num

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/case-file-view-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/case-file-view-folder/case-file-view-folder.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/test-data/categories-and-documents-test-data.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/test-data/document-tree-node-test-data.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/unsupported-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/utils/date.pipe.ts

https://tools.hmcts.net/jira/browse/EXUI-2672
Fix bug in ccdDate pipe that ignores local offset when a format string is provided
Remove unnecessary Angular DatePipe reference that seems only to be needed to handle local date conversion, but has a bug on the last day of the year.
```
[ ] Yes
[x] No
```

Fix date error in case file view

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit/case-edit.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/event-completion-state-machine.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts

https://tools.hmcts.net/jira/browse/EXUI-1717
add WA related logs
```
[ ] Yes
[x] No
```

exui-1717-add WA related logs

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/history/event-log/event-log.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/history/event-log/event-log.scss

https://tools.hmcts.net/jira/browse/EXUI-2734
Improve event history screen by applying vertical scrollbar to event history div.
```
[ ] Yes
[x ] No
```

exui-2734 - Apply vertical scrollbar to event history div

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/pagination/pagination.component.html

https://tools.hmcts.net/jira/browse/EXUI-1562
```
[ ] Yes
[ x ] No
```

WIP:removes role attribute & updates version

---

.github/workflows/npmpublish.yml
RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts

https://tools.hmcts.net/jira/browse/EXUI-2766
Add ignore case to regex creation so users can upload files with upper case file extension

EXUI-2766 

---

package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EXUI-1602?src=confmacro
User release MV

EXUI-1602 - Use release TK for 1602, update release version

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/case-file-view-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-date-input/query-write-date-input.component.html

https://tools.hmcts.net/jira/browse/EXUI-2765
https://tools.hmcts.net/jira/browse/EXUI-1227
https://tools.hmcts.net/jira/browse/EXUI-1994
release 
```
[ ] Yes
[x] No
```

Release toolkit 26 02 25

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.ts

EXUI-2792
Various fixes to task completion
```
[ ] Yes
[x] No
```

Fixes to completion

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/shared/case-file-view-overlay-menu/case-file-view-overlay-menu.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/components/shared/case-file-view-overlay-menu/case-file-view-overlay-menu.component.ts

https://tools.hmcts.net/jira/browse/EXUI-1573
```
[ ] Yes
[ x ] No
```

WIP:adds changes for overlay menu items

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/pagination/pagination.component.html

https://tools.hmcts.net/jira/browse/EXUI-1627
```
[ ] Yes
[ x ] No
```

WIP:adds aria label for current page

---

projects/ccd-case-ui-toolkit/src/lib/shared/components/case-list/case-list.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-list/case-list.component.spec.ts

https://tools.hmcts.net/jira/browse/EXUI-1649
```
[ ] Yes
[ x ] No
```

WIP:updates the case-list labels for checkboxes

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts

https://tools.hmcts.net/jira/browse/EXUI-2902
Ignore warning and go button not working for 2 events
```
[ ] Yes
[x] No
```

exui-2902-Ignore warning and go button not working

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/complex/write-complex-field.html

https://tools.hmcts.net/jira/browse/EXUI-2147
```
[ ] Yes
[ x ] No
```

WIP:changes field so ouput only happens when value is present

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

media viewer change

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/services/event-trigger.resolver.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/services/event-trigger.resolver.ts

https://tools.hmcts.net/jira/browse/EXUI-2987
Add additional check for case id to event trigger cache logic

EXUI-2987 - fix, update ver to pre-release

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/services/work-allocation.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/services/case.resolver.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/create-case-filters/create-case-filters.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/history/event-log/event-log-table.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-details/query-details.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/services/activity/activity.service.ts
projects/ccd-case-ui-toolkit/src/lib/shared/utils.ts

https://tools.hmcts.net/jira/browse/EXUI-2972
Replace the userIsCaseworker method with a suitable utils function and refactor relevant code
```
[ ] Yes
[ x ] No
```

Add the isInternalUser changes

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/markdown/markdown.component.ts

https://tools.hmcts.net/jira/browse/EXUI-3004
Links for a new tab causing issues redirecting existing tab
```
[ ] Yes
[x] No
```

exui-3004-link issue

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.ts

https://tools.hmcts.net/jira/browse/EXUI-3161
```
[ ] Yes
[ ] No
```

fix no task error found

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.ts

https://tools.hmcts.net/jira/browse/EXUI-3301
```
[ ] Yes
[ ] No
```

fix caching issue

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.spec.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/document/write-document-field.component.ts

https://tools.hmcts.net/jira/browse/EXUI-3304
Fix error message when not using CDAM

EXUI-3304 - fix error message

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-case-details-header/query-case-details-header.component.ts
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-check-your-answers/query-check-your-answers.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-raise-query/query-write-raise-query.component.html
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/components/query-write/query-write-respond-to-query/query-write-respond-to-query.component.html

https://tools.hmcts.net/jira/browse/EXUI-3311
```
[ ] Yes
[ ] No
```

extra text removed; missing case header fixed

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

update to use tk release

---

package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.html

https://tools.hmcts.net/jira/browse/EXUI-3389
```
[ ] Yes
[ ] No
```

EXUI-3389: missing footer copy fixed

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/read-query-management-field.component.html

https://tools.hmcts.net/jira/browse/EXUI-3398
```
[ ] Yes
[ ] No
```

copy update

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/query-management/utils/query-management.utils.ts

https://tools.hmcts.net/jira/browse/EXUI-3387
```
[ ] Yes
[ ] No
```

EXUI-3387: fixed spacing issue

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

https://tools.hmcts.net/jira/browse/EXUI-2836
Test pr for EXUI-2836
```
[ ] Yes
[ ] No
```

EXUI-2836 - use pre-release media-viewer

---

RELEASE-NOTES.md
package.json
projects/ccd-case-ui-toolkit/package.json
yarn.lock

EXUI-2469 use release mv
