RELEASE-NOTES.md, package.json, src/shared/case-editor/case-edit-page.component.spec.ts, src/shared/case-editor/case-edit-page.component.ts, src/shared/case-editor/case-edit-page.html, src/shared/case-editor/case-edit-submit.component.spec.ts, src/shared/case-editor/case-edit-submit.component.ts, src/shared/case-editor/case-edit-submit.html
https://tools.hmcts.net/jira/browse/RDM-3178
https://tools.hmcts.net/jira/browse/RDM-3179
'Cancel and Return' functionality is enabled when Save and Resume is not configured	
As a user I want to 'Cancel and Return' only on a create event
bug fix to cancel on CYA page of create case event with S&R: Release new version
```
[ ] Yes
[ ] No
```
=> Rdm 3178 + RDM 3179 + bug fix to cancel on CYA page of create case event with S&R: Release new version

.travis.yml
RDM-3092
https://tools.hmcts.net/jira/browse/RDM-3093
```
[ ] Yes
[ ] No
```
=> Drop NodeJS 8.9.4 as 8.11.1 is the new default

.gitignore, RELEASE-NOTES.md, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/RDM-3463.
Fixes vulnerability where `compodoc` is dependent on a version of `live-server` that is dependent on a compromised version of `event-stream`.
```
[ ] Yes
[x] No
```
=>  RDM-3463: Update dependency on compodoc to Version 1.1.7

src/shared/components/palette/fixed-radio-list/write-fixed-radio-list-field.html
https://tools.hmcts.net/jira/browse/RDM-3391
Steps:
Load definition file with FixeRadioList component for Create Case page
Login into the Web app
Go to Create case page to view the component
Click on Radio label text to select the radio option (not on the circle button)
Expected:
Radio list option should be selectable on label text click (Ref. https://design-system.service.gov.uk/components/radios/)
Actual:
Radio list option is not selected when clicked on a label text
```
[ ] Yes
[X] No
```
=> RDM-3391 - BugFix- Selecting radio label will select radio button now

src/shared/components/palette/label/label-field.component.spec.ts, src/shared/components/palette/label/label-field.html, src/shared/directives/substitutor/label-substitutor.directive.spec.ts, src/shared/directives/substitutor/label-substitutor.directive.ts, src/shared/directives/substitutor/services/label-substitution.service.spec.ts, src/shared/directives/substitutor/services/label-substitution.service.ts
https://tools.hmcts.net/jira/browse/RDM-2323
Full Name
As a court staff user,
When I view WorkBasketResults or SearchResults screens
I expect to see the citizens first name and last name joined together as a well formed full name.
And the full name is displayed in a single column
Note:- Due to certain changes failing breaking when merging code from master , I have created a branch from master and copied those changes individually on it.Tested it again locally.
```
[ ] Yes
[X] No
```
=> Rdm 2323 based on latest master

.travis.yml
This ensure a build will fail if yarn.lock needs updating during `yarn
install`.  This should also ensure that anyone doing `yarn add` will
only be commiting changes that actually were caused by the add not by a
micreant install.
=> Ensure yarn.lock is kept up-to-date

demo/src/app/app.config.ts, src/app.config.ts, src/shared/components/case-editor/case-create/case-create.component.spec.ts, src/shared/components/case-editor/case-create/case-create.component.ts, src/shared/services/draft/draft.service.spec.ts, src/shared/services/draft/draft.service.ts
https://tools.hmcts.net/jira/browse/RDM-3574
Data Store + UI Toolkit: Post/Put/Get/Delete Draft endpoint in API v2
v2 endpoints:
POST /case-types/{ctid}/drafts
PUT /case-types/{ctid}/drafts/{did}
GET /drafts/{did}
DELETE /drafts/{did}
To do:
Produces custom vnd media type
Use HATEOAS/HAL resource
Swagger doc annotation
Functional tests
```
[ ] Yes
[x] No
```
=> RDM-3574 Consume new V2 draft endpoints

RELEASE-NOTES.md, package.json, src/shared/components/palette/case-link/read-case-link-field.component.spec.ts, src/shared/components/palette/case-link/read-case-link-field.component.ts, src/shared/components/palette/case-link/read-case-link-field.html
RDM-3628
- Add null check to case links to make them safe to use in case list
- Add tests for read CaseLink component
```
[ ] Yes
[x] No
```
=> RDM-3628: Add null check for CaseLinks

src/polyfills.ts, src/shared/components/case-viewer/case-event-trigger/case-event-trigger.component.ts, src/shared/components/case-viewer/case-viewer.component.ts, src/shared/services/activity/activity.polling.service.spec.ts, src/shared/services/activity/activity.polling.service.ts
https://tools.hmcts.net/jira/browse/RDM-3430
within the activity service, run rx-js polling outside the angular zone so that it does not continuously trigger change detection as this breaks the waiting mechanism in the protractor functional tests.
```
[ ] Yes
[x] No
```
=> run polling outside angular zone to fix protractor tests

src/shared/services/form/form-validators.service.ts
https://tools.hmcts.net/jira/browse/RDM-3325
As part of the ticket RDM-3325, corrected the regex to fix the validation fail in firefox  
```
[ ] Yes
[x] No
```
=> RDM-3325-firefox-fix: Firefox issue of regex is fixed

.travis.yml
Node 12.x has some dependency build issues.  Allow failures here until
those are fixed.
```
[ ] Yes
[ ] No
```
=> Allow failure on latest node

src/shared/components/palette/document/write-document-field.component.spec.ts
Fix for failing unit tests on travis due to an automatic upgrade of chrome to V75
n/a
Strongly Type test data to File type as this was causing tests to break following an upgrade to chrome v75
```
[ ] Yes
[X] No
```
=> Strongly Type test data to File type

.travis.yml
In order todo a prerelease there needs to be a build from the branch. we are reverting this pr to bring back branch builds for this reason
=> Revert "Build on master and tagged releases" - Allowing prereleases 

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/RDM-4906
Payments has released a new version of web-compnent v1.8.5 v1.8.6
https://www.npmjs.com/package/@hmcts/ccpay-web-component
Please integration this new version 1.8.5 1.8.6 to support telephony payments details.
New version has support to view telephony payments in CCD.
```
[ ] Yes
[X] No
```
=> RDM-4906 - First cut of ccpay-web-component version upgrade to 1.8.6

RELEASE-NOTES.md, package.json, src/shared/components/palette/fixed-list/write-fixed-list-field.html
https://tools.hmcts.net/jira/browse/RDM-4525
Remove superfluous id from write-fixed-list-field template. Not needed by FE func tests as there is already same id present on select tag.
```
[ ] Yes
[x] No
```
=> RDM-4525 Remove unused id as breaking external tests.

RELEASE-NOTES.md, package.json, src/shared/components/palette/base-field/field-read.component.ts, src/shared/components/search-result/search-result.component.html, src/shared/components/search-result/search-result.component.ts
https://tools.hmcts.net/jira/browse/RDM-5044
Field interpolation is broken on workbasket results
This is ensuring all field values are resolved by label interpolation before the component is fully initialised.
```
[ ] Yes
[x] No
```
=> RDM-5044 Add Promise then for Angular lifecycle to catchup.

RELEASE-NOTES.md, package.json, src/shared/components/palette/address/write-address-field.component.ts, src/shared/components/palette/address/write-address-field.html
https://tools.hmcts.net/jira/browse/RDM-4692
ccd-write-address-field is composing ccd-write-complex-type-field, so we do not need to alter the prefix. ccd-write-complex-type-field will do it.
```
[ ] Yes
[X ] No
```
=> RDM-4692 ccd-write-address-field id fix

RELEASE-NOTES.md, package.json, src/shared/components/palette/base-field/field-read.component.ts
https://tools.hmcts.net/jira/browse/RDM-5604
CaseField Instantiation with Curly braces causes an issue since curly brace instantiation creates a plain object with no isComplex or isCollection methods. Added a fix for making sure caseField of component is an instance of CaseField by explicit casting...
These are the components using "{}" instantiation
- read-collection-field
- read-complex-field-collection-table
```
[ ] Yes
[X] No
```
=> RDM-5604 Fix {} instantiations for read-collection-XX components

RELEASE-NOTES.md, package.json, src/shared/components/case-editor/services/wizard-page-field-to-case-field.mapper.ts, src/shared/components/palette/base-field/field-read-label.html, src/shared/components/palette/base-field/field-read.html, src/shared/components/palette/collection/collection-create-checker.service.spec.ts, src/shared/components/palette/collection/collection-create-checker.service.ts, src/shared/components/palette/collection/write-collection-field.component.spec.ts, src/shared/components/palette/collection/write-collection-field.component.ts, src/shared/components/palette/complex/read-complex-field-collection-table.html, src/shared/components/palette/complex/read-complex-field-table.component.ts, src/shared/components/palette/complex/read-complex-field-table.html, src/shared/components/palette/complex/read-complex-field.component.spec.ts, src/shared/components/palette/complex/read-complex-field.component.ts, src/shared/components/palette/complex/read-complex-field.html, src/shared/components/palette/palette.module.ts, src/shared/fixture/shared.test.fixture.ts
https://tools.hmcts.net/jira/browse/RDM-5310
This PR fixes two things, 
- Firstly the `contextFields` for the read type complex field renderers (like read-complex-field-table) were reduced to the child field but as dot notation has been introduced the context fields must include all fields so that directives like conditional Hide  and show od legal field substitutor could evaluate correctly
- Fixing this introduced another issue, even though some of the fields were marked as `HIDDEN` they were still being shown in the page. For this `hidden` is honoured for read type complex field renderers.
- Finally since the fields are marked as `READONLY` by the `ccd-data-store-api` when the user has no update write, while adding new collection item the fields weren't rendering correctly. That has …
=> RDM-5310 Fix for Proceed button does not render correctly

src/shared/components/palette/collection/write-collection-field.component.ts
having a collection in the dynamic workbasket filters causes an error and grey screen when clicking 'create case' button. as the ngOnDestroy us trying to unsubscribe to a subscription that has never been initialised, this hot fix seems to resolve the problem and has unblocked testing 
```
[ ] Yes
[ ] No
```
=> Rdm 4617 fix

demo/src/style/app.scss, src/shared/components/palette/document/write-document-field.component.ts
RDM-5709: Previously uploaded Document links are lost when uploading additional documents in an event
[RDM-5709] (https://tools.hmcts.net/jira/browse/RDM-5709).
related issue:
RDM-5398.
This PR contains big changes in generic components. Regression test is needed .
=> Rdm 5709 based rc 15.2

demo/server.js, demo/src/app/case-view-consumer.component.html, demo/src/app/case-view-consumer.component.ts, demo/stubs/api.json, src/shared/components/case-viewer/case-view/case-view.component.html, src/shared/components/case-viewer/case-view/case-view.component.spec.ts, src/shared/components/case-viewer/case-view/case-view.component.ts, src/shared/components/case-viewer/case-viewer.component.ts
https://tools.hmcts.net/jira/browse/RDM-6350
Changes required to properly consume CaseViewerComponent by external UI like ExUI.
The changes would require the consuming component (see encapsulated inside CaseViewConsumerComponent in demo app) to implement navigation listening logic on the following navigation events:
- DRAFT_DELETED,
- ERROR_DELETING_DRAFT,
- DRAFT_RESUMED,
- EVENT_TRIGGERED,
- NO_READ_ACCESS_REDIRECTION,
as well as handle and pass down any errors resulting from the navigation.
Note: A new failCallback event has been added to showcase the error handling mechanism when navigation fails with 422 and there are callback errors and warnings returned which results in the error being passed down to the CaseViewerComponent and displayed on the template as banners.
**Does this PR …
=> Rdm 6350 non ccd use

RELEASE-NOTES.md, demo/src/app/search-result-consumer.component.html, demo/src/app/search-result-consumer.component.ts, package.json, src/shared/components/search-result/search-result.component.html, src/shared/components/search-result/search-result.component.spec.ts, src/shared/components/search-result/search-result.component.ts
https://tools.hmcts.net/jira/browse/RDM-6084
Removed the clickCase EventEmitter from the search-result component and introduced caseLinkUrlTemplate Input for passing the url template.
```
[ ] Yes
[ X] No
```
=> RDM-6084 Fix for a caseLink to open the case in new tab.

RELEASE-NOTES.md, package.json, src/shared/components/case-editor/services/cases.service.spec.ts, src/shared/components/case-editor/services/cases.service.ts, src/shared/components/case-viewer/printer/case-printer.component.spec.ts, src/shared/components/case-viewer/printer/case-printer.component.ts
https://tools.hmcts.net/jira/browse/RDM-5883
Consume external GET Printable Documents endpoint in API v2
```
[x] Yes
[ ] No
```
=> RDM-5883 Consume external GET Printable Documents endpoint in API v2

src/shared/components/case-editor/services/wizard-page-field-to-case-field.mapper.spec.ts, src/shared/components/case-editor/services/wizard-page-field-to-case-field.mapper.ts
https://tools.hmcts.net/jira/browse/RDM-5007
Use caseField displayContext instead using the override from wizardPageField.display_context. Final goal is to remove the wizardPageField.display_context from wizardPages.
```
[ ] Yes
[X ] No
```
=> RDM-5007 Stop using wizardPageField.display_context

RELEASE-NOTES.md, package.json, src/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts, src/shared/components/case-editor/case-edit-page/case-edit-page.html, src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts, src/shared/components/case-editor/case-edit-submit/case-edit-submit.html, src/shared/components/case-viewer/case-viewer.component.html, src/shared/components/case-viewer/case-viewer.component.spec.ts, src/shared/components/error/callback-errors.html
https://tools.hmcts.net/jira/browse/EUI-2344
Hide the generic callback error message if a custom configured one has been provided by a Service. Applies to the Case Edit page, Case Edit Submit page, and Case Viewer component.
```
[ ] Yes
[x] No
```
=> EUI-2344: Hide generic callback error message

RELEASE-NOTES.md, package.json, src/shared/services/search/search.service.spec.ts, src/shared/services/search/search.service.ts
https://tools.hmcts.net/jira/browse/EUI-2649
Change `use_case` query parameter back to `usecase`, due to reversion on CCD Demo environment.
```
[ ] Yes
[x] No
```
=> EUI-2649: Revert EUI-2575 temporarily

RELEASE-NOTES.md, package.json, src/shared/services/search/search.service.spec.ts, src/shared/services/search/search.service.ts
https://tools.hmcts.net/jira/browse/EUI-2657
Revert `usecase` query parameter to `use_case`, in line with reversion on CCD Demo environment being undone.
```
[ ] Yes
[x] No
```
=> EUI-2657: Reinstate EUI-2575

RELEASE-NOTES.md, package.json, src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.spec.ts, src/shared/components/case-editor/case-edit-submit/case-edit-submit.component.ts, src/shared/components/case-editor/case-edit/case-edit.component.spec.ts, src/shared/domain/definition/case-field.model.ts, src/shared/fixture/shared.test.fixture.ts, src/shared/services/fields/fields.purger.ts
https://tools.hmcts.net/jira/browse/EUI-1783
Ensure any existing value of a hidden field is deleted in the CCD backend, unless the field has the `retain_hidden_value` flag set to `true` (see RDM-9024), in which case the existing value will remain untouched.
**Note:** This is a _breaking change_; for hidden fields, the default behaviour will change from the value being retained to the value being **deleted** in the CCD backend, _unless_ the field has the `retain_hidden_value` flag set to `true`.
```
[x] Yes
[ ] No
```
=> EUI-1783: Support for deleting hidden field values

RELEASE-NOTES.md, package.json, src/shared/services/fields/fields.purger.ts
https://tools.hmcts.net/jira/browse/EUI-2681
Change the check to see if the form control is a `FormControl` instance (simple field) _or something else_. This caters for other types of form controls, such as `FormArray` (and not just `FormGroup`).
```
[ ] Yes
[x] No
```
=> EUI-2681: Fix another bug with check for complex field types

package.json, src/shared/components/case-editor/services/cases.service.spec.ts, src/shared/components/markdown/markdown.html, src/shared/components/workbasket-filters/workbasket-filters.component.html, src/shared/components/workbasket-filters/workbasket-filters.component.spec.ts, src/shared/components/workbasket-filters/workbasket-filters.component.ts
https://tools.hmcts.net/jira/browse/EUI-2569
https://tools.hmcts.net/jira/browse/EUI-2646
https://tools.hmcts.net/jira/browse/EUI-3024
filter controls' selected values are remembered when you return to the case list search page
label now retained in case heading tab
"any" option for case state is back, and added functionality to search all case states when this is selected.
```
[ ] Yes
[ x] No
```
=> fixes for the case list search page and case details page

src/shared/services/form/form-value.service.ts
https://tools.hmcts.net/jira/browse/EUI-3375
Reintroduced the recursion within collections to clear out unwanted fields within the `value` part of the item. This had been removed due to EUI-3284 but we still need to remove nested labels because the API doesn't like them.
EUI-3284 still failed with just that change so I've added in a check for the display_context being set to 'HIDDEN' when considering whether to delete a hidden field's data at the submission stage. When the display_context is set to 'HIDDEN', it means that it's been overridden by the page wizard to not be seen by the user, rather than having been hidden by the normal show/hide logic.
There are instances where sending hidden data causes the API to return an error - i.e., data has been submitted that shouldn't have been - …
=> EUI-3375: Clear out labels nested within complex types within collections

RELEASE-NOTES.md, package.json, src/shared/services/alert/alert.service.ts
https://tools.hmcts.net/jira/browse/EUI-3381
Alerts weren't showing because MC still relies on the alertObserver, which wasn't being updated when error, warning, or success were called.
```
[ ] Yes
[x] No
```
=> EUI-3381: Alerts not showing

RELEASE-NOTES.md, package.json, src/shared/components/palette/document/write-document-field.component.ts
https://tools.hmcts.net/jira/browse/EUI-3403
Document fields were not being registered when there was no value and the field itself was not mandatory, which meant that `show_conditions` would not be evaluated. Cleaned up the logic and the field is now always registered.
Also fixed a lint error in this PR.
```
[ ] Yes
[x] No
```
=> EUI-3403: Fix for optional top level documents

RELEASE-NOTES.md, package.json, src/shared/services/document-management/document-management.service.ts
https://tools.hmcts.net/jira/browse/EUI-3464
Do not set `Accept` and `Content-Type` headers with `null` values; this is not permitted by the Angular HttpClient. Just pass a new HttpHeaders object in the request and Angular will do the rest.
```
[ ] Yes
[x] No
```
=> EUI-3464: Remove setting of null HTTP headers

RELEASE-NOTES.md, package.json, src/shared/services/request/request.options.builder.ts
https://tools.hmcts.net/jira/browse/EUI-3490
The previous implementation used `URLSearchParams`, which automatically ignored `null` properties. Switching to `HttpParams` introduced an issue where such `null`s are not ignored, which had the consequence of sending `"&state=null"` in the query string when the user selected "Any" in the State filter.
Rather than revert back to the deprecated `URLSearchParams` or refactor additional areas for the now built-in `URLSearchParams`, I'm just `null`-checking and making sure they don't get into the query string.
```
[ ] Yes
[x] No
```
=> EUI-3490: Case list filter broken

RELEASE-NOTES.md, package.json, src/shared/components/case-editor/services/cases.service.spec.ts, src/shared/components/case-editor/services/cases.service.ts, src/shared/components/case-history/services/case-history.service.ts, src/shared/services/banners/banners.service.ts, src/shared/services/document-management/document-management.service.ts, src/shared/services/draft/draft.service.ts, src/shared/services/profile/profile.service.ts, src/shared/services/search/search.service.ts, src/shared/services/workbasket/workbasket-input-filter.service.ts
https://tools.hmcts.net/jira/browse/EUI-3494
https://tools.hmcts.net/jira/browse/EUI-3495
Fix for case creation that was broken when moving from `Http` to `HttpClient`. This was also a problem for the completion of events on the case.
In the midst of this, tidied up some additional points where changes had been made but code had been left in that was redundant (e.g., `map(response => response)` is a dead operation) or confusing (in the same example, it wasn't actually the _response_, it was the response's _body_.)
```
[ ] Yes
[x] No
```
=> EUI-3494, EUI-3495: Case creation broken

src/shared/components/palette/history/event-log/event-log-table.component.spec.ts, src/shared/components/palette/utils/date.pipe.spec.ts, src/shared/components/palette/utils/date.pipe.ts, src/shared/directives/substitutor/label-substitutor.directive.spec.ts
https://tools.hmcts.net/jira/browse/EUI-2667
The DatePipe was throwing exceptions for dates that didn't fit the ISO format. This resulted in console errors and a failure to display dates when they are in a collection - the date is basically formatted twice, except the second time it throws an exception because it receives the already-formatted date.
This will now attempt to parse dates it receives that don't correspond to the ISO format and, when it encounters one, format it appropriately.
```
[ ] Yes
[x] No
```
=> EUI-2667 - Fix for collection fields that include date fields

RELEASE-NOTES.md, package.json, src/shared/components/palette/utils/date.pipe.spec.ts, src/shared/components/palette/utils/date.pipe.ts, src/shared/directives/substitutor/label-substitutor.directive.spec.ts
https://tools.hmcts.net/jira/browse/EUI-2667 ✅ `DONE`
The `DatePipe` was throwing exceptions for dates that didn't fit the ISO format. This resulted in console errors and a failure to display dates when they are in a collection - the date is basically formatted twice, except the second time it throws an exception because it receives the already-formatted date.
This will now attempt to parse dates it receives that don't correspond to the ISO format and, when it encounters one, format it appropriately.
```
[ ] Yes
[x] No
```
**Notes**
This is a Draft PR for the moment as the original went stale after not being merged, despite the JIRA having been tested and approved. I've now rebased it against `master` so it should be …
=> EUI-2667: DatePipe fix

RELEASE-NOTES.md, package.json, src/shared/components/case-viewer/case-viewer.component.spec.ts, src/shared/components/error/callback-errors.component.spec.ts, src/shared/domain/http/http-error.model.spec.ts, src/shared/domain/http/http-error.model.ts, src/shared/services/http/http-error.service.spec.ts, src/shared/services/http/http-error.service.ts, src/shared/services/http/http.service.spec.ts, src/shared/services/http/http.service.ts
https://tools.hmcts.net/jira/browse/EUI-3594
Fix issue with HTTP error handling post-Angular `HttpClient` upgrade, which failed to map error properties between new `HttpErrorResponse` objects being returned and `HttpError` domain model objects for UI display.
```
[ ] Yes
[x] No
```
=> EUI-3594: Error message specifics not being displayed

RELEASE-NOTES.md, demo/src/app/app.config.ts, package.json, src/app.config.ts, src/shared/components/case-viewer/printer/case-printer.component.spec.ts, src/shared/components/case-viewer/printer/pipes/print-url.pipe.spec.ts, src/shared/components/case-viewer/printer/pipes/print-url.pipe.ts
https://tools.hmcts.net/jira/browse/EUI-3587
Fix the pipe to rewrite remote Print Service URLs to the correct "local" version to be used for the front-end, irrespective of environment-based variations of the remote domain name.
```
[ ] Yes
[x] No
```
=> EUI-3587: Fix "Print URL" pipe for rewriting remote Print Service URLs

src/shared/directives/substitutor/label-substitutor.directive.spec.ts, src/shared/services/fields/fields.utils.spec.ts, src/shared/services/fields/fields.utils.ts
N/A, but issue identified here: https://github.com/hmcts/ccd-case-ui-toolkit/pull/618
Fixed an issue with how `MoneyGBP` fields are rendered as it failed to render correctly for a numeric value of zero and could also weirdly stringify a return value because of the return type.
```
[ ] Yes
[x] No
```
=> MoneyGBP issue

RELEASE-NOTES.md, package.json, src/shared/components/palette/collection/write-collection-field.component.ts, tsconfig-aot.json
https://tools.hmcts.net/jira/browse/EUI-3983
When a collection that contains complex fields is added as part of a collection the fields with show condition are momentarily displayed before the `conditional-show-form.directive.ts` kicks in and hides it. This is because the subscription has a debounce(100) on it. The debounce is there to help performance.
As I saw it, there are two fixes to this bug, remove the debounce or default added collection complex fields to hidden = true for fields that have show_condition logic. I chose the latter because I think is more sustainable and I know that the show/hide logic all being changed soon too so this fix will withstand the changes to the current directive.
```
[ ] Yes
[x-x-x] No …
```
=> defaulted hidden state for added complex fields in collection to false

RELEASE-NOTES.md, package.json, src/shared/components/palette/complex/read-complex-field-table.html
https://tools.hmcts.net/jira/browse/EUI-4227
Removed `topLevelFormGroup` from the binding in `read-complex-field-table.html`. Will need some proper regression testing!
```
[ ] Yes
[x] No
```
=> EUI-4227: Missing elements

package.json, src/shared/directives/conditional-show/conditional-show.directive.ts, src/shared/services/fields/fields.utils.ts, src/shared/services/form/form-value.service.spec.ts, src/shared/services/form/form-value.service.ts
https://tools.hmcts.net/jira/browse/EUI-4244
Initial fix (identified by @RiteshHMCTS) was to appropriately clear out complex objects that have null values when posting mid-event callbacks. Not doing this caused problems for "optional" fields that were mandatory based on some business logic within CCD.
This then presented with a different issue in `release-4.1.0` as a result of getting label interpolation working for multi-selects. In order to sorted this, added a method to clear out properties that are only there for the multi-select labels when submitting data, either as part of a mid-event callback or at the end of the flow after Check Your Answers.
```
[ ] Yes
[x] No
```
=> EUI-4244: Mid-event callback error

package.json, src/shared/components/palette/date/write-date-container-field.component.spec.ts, src/shared/components/palette/datetime-picker/datetime-picker-component.spec.ts, src/shared/components/palette/datetime-picker/datetime-picker-utils.ts, src/shared/components/palette/datetime-picker/datetime-picker.component.ts, src/shared/components/palette/palette.module.ts
https://tools.hmcts.net/jira/browse/EUI-4279
updated tag, removed moment adapter and updated datepicker to es5 version eg @angular-material-components/datetime-picker/esm5/angular-material-components-datetime-picker.js to work with IE 11
```
[ ] Yes
[x] No
```
=> Release 4.1.1-IE 11 fix

package.json, src/shared/components/palette/date/write-date-container-field.component.spec.ts, src/shared/components/palette/datetime-picker/datetime-picker-component.spec.ts, src/shared/components/palette/datetime-picker/datetime-picker-utils.ts, src/shared/components/palette/datetime-picker/datetime-picker.component.ts, src/shared/components/palette/palette.module.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4279
downgraded to "@angular-material-components/datetime-picker": "^2.0.4" and "@angular-material-components/moment-adapter": "^4.0.1" for ie 11 fix
```
[ ] Yes
[ ] No
```
=> Release 4.1.2 - ie fix for date components

RELEASE-NOTES.md, package.json, src/shared/domain/http/http-error.model.ts, src/shared/services/activity/activity.service.ts, src/shared/services/http/http-error.service.ts, src/shared/services/http/http.service.spec.ts, src/shared/services/http/http.service.ts
https://tools.hmcts.net/jira/browse/EUI-4226
Fixed an issue with the error message coming from the Activity Tracker coming back with a 403 but it getting stripped out in the `HttpError.from(...)` method.
```
[ ] Yes
[x] No
```
Linked to https://github.com/hmcts/rpx-xui-webapp/pull/1200.
=> EUI-4226: Activity tracker polls unauthorised users continuously

RELEASE-NOTES.md, package.json, src/app.config.ts, src/shared/components/palette/document/document-url.pipe.spec.ts, src/shared/components/palette/document/document-url.pipe.ts, src/shared/components/palette/document/read-document-field.component.spec.ts, src/shared/services/document-management/document-management.service.spec.ts, src/shared/services/document-management/document-management.service.ts
- https://tools.hmcts.net/jira/browse/EUI-4161
- add getHrsUrl/getRemoteUrl functions to enable rewriting of em-hrs-api URLs, in a similar fashion to dm-store URLs
```
[ ] Yes
[X] No
```
=> EUI-4161 HRS for master

RELEASE-NOTES.md, package.json, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.html, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.scss, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.spec.ts, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.ts, src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts, src/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts, src/shared/components/palette/case-flag/domain/case-flag-state.model.ts, src/shared/components/palette/case-flag/write-case-flag-field.component.html, src/shared/components/palette/case-flag/write-case-flag-field.component.ts
[EUI-5654](https://tools.hmcts.net/jira/browse/EUI-5654)
Integrate with "list of values" data for selected flag types (currently only language ones) from Reference Data, so that this step is displayed only for those particular flag types.
```
[ ] Yes
[x] No
```
=> EUI-5654: Create Case Flag - "Search for a language interpreter" step integration

RELEASE-NOTES.md, package.json, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.html, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.spec.ts, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.ts, src/shared/components/palette/case-flag/enums/index.ts, src/shared/components/palette/case-flag/enums/search-language-interpreter-error-message.enum.ts
[EUI-4849](https://tools.hmcts.net/jira/browse/EUI-4849)
Add validation to language search and manual language inputs of the "Search for a language interpreter" step.
```
[ ] Yes
[x] No
```
=> EUI-4849: Create Case Flag - "Search for a language interpreter" step validation

RELEASE-NOTES.md, package.json, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.html, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.spec.ts, src/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.ts, src/shared/components/palette/case-flag/enums/search-language-interpreter-error-message.enum.ts, src/shared/components/palette/case-flag/read-case-flag-field.component.ts
[EUI-5647](https://tools.hmcts.net/jira/browse/EUI-5657)
Add validation to prevent both language selection and manual language entry at the same time. Also ensure manual language entry value is cleared if "Enter the language manually" checkbox is unchecked.
```
[ ] Yes
[x] No
```
=> EUI-5657: Create Case Flag - "Search for a language interpreter" step validation

RELEASE-NOTES.md, package.json, src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.html, src/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.spec.ts, src/shared/services/fields/fields.utils.spec.ts, src/shared/services/fields/fields.utils.ts
[EUI-7210](https://tools.hmcts.net/jira/browse/EUI-7210)
[EUI-7225](https://tools.hmcts.net/jira/browse/EUI-7225)
EUI-7210: Fix mapping of case field to flags object to handle `null` or `undefined` CaseField `value` property; EUI-7225: Fix to display party role (if provided) alongside party name for party-level flags options on "Select flag location" page.
```
[ ] Yes
[x] No
```
=> EUI-7210/EUI-7225: Case Flags defect fixes

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/case-flag-status.enum.ts
[EUI-7347](https://tools.hmcts.net/jira/browse/EUI-7347)
[EUI-7570](https://tools.hmcts.net/jira/browse/EUI-7570)
Support display of new "Not approved" status for Case Flags.
```
[ ] Yes
[x] No
```
=> EUI-7347/EUI-7570: Case Flags v2 - New "Not approved" status

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-file-view/case-file-view-field-read.component.ts
[EUI-7417](https://tools.hmcts.net/jira/browse/EUI-7417)
Ensure document move functionality is disabled when Case File View component is in readonly mode.
```
[ ] Yes
[x] No
```
=> EUI-7417: Case File View - Disable document move functionality

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.ts
[EUI-7796](https://tools.hmcts.net/jira/browse/EUI-7796)
Fix flag types retrieval to use `HMCTSServiceId` from supplementary data in the first instance (if available); this caters for case types that are associated with multiple HMCTS service codes.
```
[ ] Yes
[x] No
```
=> EUI-7796: Case Flags - Fix flag types retrieval for case types with multiple HMCTS service codes

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/confirm-flag-status/confirm-flag-status.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/search-language-interpreter/search-language-interpreter.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-location/select-flag-location.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag-welsh-translation-form/update-flag-welsh-translation-form.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag-welsh-translation-form/update-flag-welsh-translation-form.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-error-message.enum.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/enums/update-flag-step.enum.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/read-case-flag-field.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts
EUI-7777
EUI-7842
EUI-7900
EUI-7777: Change wording for "translation needed" checkbox on "Update flag" page; EUI-7842: Remove read-only setting from English description and comments boxes on "Add Welsh translation to flag" page; EUI-7900: Add validation to "Update flag" page.
```
[ ] Yes
[x] No
```
=> EUI-7777/EUI-7842/EUI-7900: Case Flags v2 - UI amendments for Manage Case Flags pages

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
EUI-7354
Ensure flags with a status of either "Inactive" or "Not approved" are filtered out from display on "Manage case flags" page, so they cannot be selected for update.
```
[ ] Yes
[x] No
```
=> EUI-7354: Case Flags v2 - Filter out "Inactive" and "Not approved" flags from selection

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/case-editor/case-edit-page/case-edit-page.component.ts
EUI-8738
Ensure that all instances of JudicialUser `FormControl`s are removed from the `FormGroup`, prior to display on the CYA page. Such `FormControl`s are added only for value selection and validation but are not intended for display otherwise (values are stored elsewhere in the data).
```
[ ] Yes
[x] No
```
=> EUI-8738: Remove JudicialUser FormControls from FormGroup displayed on "Check your answers" (CYA) page

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-table/case-flag-table.component.scss
EUI-8778
Ensure the status tag text is displayed on a single line, irrespective of screen width.
```
[ ] Yes
[x] No
```
=> EUI-8778: Prevent flag status tag text from wrapping in Case Flags table

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts
EUI-8944
Fix missing header on "Manage case flags" page when Case Flags v2.1 is enabled.
```
[ ] Yes
[x] No
```
=> EUI-8944: Case Flags v2.1 fixes

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/read-case-flag-field.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/read-case-flag-field.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.ts
EUI-8934
Fix merging of internal and external flags collections to work when a `Flags.details` array is falsy.
```
[ ] Yes
[x] No
```
=> EUI-8934: Case Flags v2.1 fixes

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/case-viewer/case-full-access-view/case-full-access-view.component.ts
EUI-8985
Fix incorrect logic for updating tab group selected index, ensuring it is done only when non-zero because zero indicates it is already selected.
```
[ ] Yes
[x] No
```
=> EUI-8985: Case Flags v2.1 fixes

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/domain/case-flag.model.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.ts
EUI-8990
Fix bug where the flag status updated via the UI is used as if it was the actual persisted status. This causes problems when a user sets the status to "Inactive" or "Not approved", then returns to an earlier point in the "Manage Case Flags" journey. `UpdateFlagComponent` displays the wrong flag status options or none at all (if "Not approved" was selected previously), and `ManageCaseFlagsComponent` no longer displays the flag in the selection list.
```
[ ] Yes
[x] No
```
=> EUI-8990: Case Flags v2 fix - Use original persisted flag status throughout "Manage Case Flags" journey

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/add-comments/add-comments.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/update-flag/update-flag.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/domain/case-flag.model.ts
EUI-8999
Restrict display of the comments visibility warning text to flags not of type "Other (internal)" for the "Create Case Flag" journey, and flags that were previously created as external for the "Manage Case Flags" journey.
```
[ ] Yes
[x] No
```
=> EUI-8999: Case Flags v2.1 fixes

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/manage-case-flags/manage-case-flags.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/read-case-flag-field.component.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/write-case-flag-field.component.ts
EUI-9020
Fix bug where previous changes to a flag are retained in the UI when the user starts over and selects the same flag to update again.
```
[ ] Yes
[x] No
```
=> EUI-9020: Case Flags v2 fix - Reset flag changes when user starts over while updating a flag

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.html, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/case-flag-summary-list/case-flag-summary-list.component.spec.ts
EUI-9061
Fix bug where Welsh description (for flags of type "Other") and Welsh comments fields are shown on the Case Flag Summary (CYA) page when a flag is updated by an external user.
```
[ ] Yes
[x] No
```
=> EUI-9061: Case Flags v2 - Case Flag Summary page fix for external user flag updates

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.spec.ts, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/case-flag/components/select-flag-type/select-flag-type.component.ts
EUI-9141
EUI-9142
Fix bug where party-level flag types are retrieved instead of case-level flag types, when "Case level" is selected for the flag location.
```
[ ] Yes
[x] No
```
=> EUI-9141/EUI-9142: Case Flags v2 - Case-level flag types not being retrieved

RELEASE-NOTES.md, package.json, projects/ccd-case-ui-toolkit/package.json, projects/ccd-case-ui-toolkit/src/lib/shared/components/palette/yes-no/write-yes-no-field.html
EUI-9165
Fix bug where nothing is shown for the yes/no field if there is no `caseField` label (should fall back on the field value).
```
[ ] Yes
[x] No
```
=> EUI-9165: Yes/no field fix
